### ISSUE TITLE
Consider what we can do for error configuration infrastructure

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#10]
Currently `KinesisMessageDrivenChannelAdapter` doesn't provide any retrying capabilities and I'm not sure that it should. 
But at the same time we can configure `errorChannel`, at least...

**Comment by JacobASeverson** [comment]
Hi @artembilan,

I'm interested in implementing `errorChannel` usage for the producer. 

Would you rather see an implementation of`com.amazonaws.handlers.AsyncHandler` within `KinesisMessageChannelBinder` that handles message passing to the `errorChannel`? Or would you rather see the `errorChannel` passed to `KinesisMessageHandler` and let that class implement the asynchronous response handling (more in line with how it is done with the Kafka binder/Spring Integration Kafka)?

Thanks!
Jacob

**Comment by artembilan** [comment]
Hello @JacobASeverson!

Well, right, would be better to have such an `AsyncHandler`, but I feel like it has to be done in the `KinesisMessageHandler` since we might need an access to the request message.

So, yes to borrow ideas from Spring Integration Kafka is the way to go.

Thank you for considering this feature!
