### ISSUE TITLE
Health Check - Suggestion

### ISSUE THREAD

**Issue by DesFieldCorbett** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#105]
I want to be able to confirm that the configured streams exist before enabling traffic to my Kinesis application. I created this health check and was wondering if it was useful or if you had a better idea. I guess it may not be useful as a generic approach as some applications may have many streams?

I am including just the check itself the rest of the Health Indicator I copied from the Kafka binder.

```
  private Health buildHealthStatus() {

    try {
      Map<String, BindingProperties> bindings = this.bindingService.getBindingServiceProperties().getBindings();
      bindings.forEach((k, v) -> client.describeStream(v.getDestination()));
      return Health.up().build();
    } 
    catch (Exception e) {
      return Health.down().build();
    }
  }
```

**Comment by artembilan** [comment]
Can you link to the code in Kafka Binder which has led you to such a solution?

Your idea really might make sense, but I need more context to understand the value.

Thanks

**Comment by DesFieldCorbett** [comment]
The Kafka one is more complex than the other HealthIndicators I have seen as it spins off a new thread:
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderHealthIndicator.java

Id be happy to do a PR if you think I am on the right track

**Comment by artembilan** [comment]
I think this is really valid in some target use-cases, but might be even dangerous as a general solution on the Binder level.

I'm not sure in the reason of such a health check in that Kafka binder as well...
Might be just a fact of an experiment when Spring Boot introduced this feature...

We really might be OK do not have some of our streams and treat the app as healthy. 

I need to investigate more about this abstraction because for me a general exception failure is OK to react for an appropriate application state...

**Comment by artembilan** [comment]
OK. After some discussion with the team, we decided to accept such a request.
We indeed can provide this kind of bean on the binder level configuration to make it explicit for the particular binder instance.

Such a bean can always be overridden into something custom.

Please, go ahead to raise a Pull Request on the matter!

Thank you for your patience and effort!

**Comment by DesFieldCorbett** [comment]
I wanted to wait till I had some experience running this before I did a PR. It seems to work well and has prevented bad deployments due to misconfigurations and typos.

However with two cavats:

-  the describeStream function is rate limited by AWS and the rate is 10 per **Account** per second:
https://docs.aws.amazon.com/kinesis/latest/APIReference/API_DescribeStream.html
so it is not really a suitable health check  - ideas welcome

- when the health check fails it would be really useful to know which one failed. Usually in a framework you would throw an exception and let the calling program log it, but due to this being a health check I cannot see how to do that. I am guess adding any logging dependecy isnt advised?

**Comment by artembilan** [comment]
>  the rate is 10 per Account per second:

That's OK. This is not what is going to be called by some internal process. Just via end-user activity.

> I am guess adding any logging dependecy isnt advised?

There is already an Apache Commons Logging dependency via Spring JCL, so, you are good to catch a `LimitExceededException` and just log it under `error()`!

**Comment by artembilan** [comment]
@DesFieldCorbett ,

any chances to see your contribution as a Pull Request?
Thanks
