### ISSUE TITLE
How to pragmatically customize KplMessageHandler?

### ISSUE THREAD

**Issue by steven-chou** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#107]
Hi, 
I want to set a custom AsyncHandler to the KplMessageHandler created by the spring aws kinesis binder. The reason is that I want to set up some custom logic to onError and onSuccess callback functions. I've looked into the source code, but couldn't find any hook or option to replace the bean, e.g. KinesisMessageChannelBinder with my own. (The setter for asyncHandler is public, but I just can't find any way to get the handle of it) Can anyone provide some inputs?

Thanks

**Comment by artembilan** [comment]
This is a functionality we need to add into this Framework.
I mean there should be an `AsyncHandler<? extends AmazonWebServiceRequest, ?>`  bean injection hook in the `KinesisMessageChannelBinder`.

Doesn't look like there is an easy way to let you to play with `KplMessageHandler` instance in your own code...
