### ISSUE TITLE
Process multiple batch records concurrently.

### ISSUE THREAD

**Issue by capmorganbih** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#111]
In our project we don't need to respect order of records in shard. Instead we need to process more records at a time than the count of shards we got. In current implementation we can set listenerMode to batch and just process List<Record> but that way we lost some useful features such as message conversion. My suggestion is to provide binder implementation with an ability to split records processing to ExecutorService. As this feature is really needed to our project needs I'm willing to contribute.

**Comment by artembilan** [comment]
I don't think that is what we would like to have on the framework level.

What you can do in your own project is something like shifting to an `ExecutorChannel`:
```
@ServiceActivator(inputChannel=Sink.INPUT, outputChannel="executorChannel")
public MyPojo consume(MyPojo payload) {
    return payload;
}

@Bean 
public MessageChannel executorChannel(Executor executor) {
     return new ExecutorChannel(executor);
}

@ServiceActivator(inputChannel="executorChannel")
public void process(MyPojo payload) {
    ...
}
```

The point is that Spring Cloud Stream Framework fully honors *Consumer Group* and *Offset* principles, so your non-standard requirement should not be as a standard option.

Thanks for understanding.

Closed as *Works as Designed*
