### ISSUE TITLE
support partitionKeyExtractorName

### ISSUE THREAD

**Issue by snyderizer** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#116]
For cases where an SpEL expression is not sufficient, it would be nice to support `org.springframework.cloud.stream.binder.PartitionKeyExtractorStrategy`, as described here: https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#spring-cloud-stream-overview-configuring-output-bindings-partitioning

Currently, if you set a configuration for `producer.partitionKeyExractorName`, a `NullPointerException` will be thrown here:

https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/b64cd10c5b5aac209b61399f81e2801f24fbbaf4/spring-cloud-stream-binder-kinesis/src/main/java/org/springframework/cloud/stream/binder/kinesis/KinesisMessageChannelBinder.java#L243

because `producerProperties.isPartitioned()` on line 234 will return `true`, but `producerProperties.getPartitionKeyExpression()` returns `null`.  

This may require duplicating some of the logic in https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/PartitionHandler.java

**Comment by artembilan** [comment]
Yes, you are right. This is a bug and for consistency with the core.
But we can't support `PartitionSelectorStrategy` because Kinesis doesn't support numbered shards:
```
    * Determines which shard in the stream the data record is assigned to. Partition keys are Unicode strings with a
     * maximum length limit of 256 characters for each key. Amazon Kinesis Data Streams uses the partition key as input
     * to a hash function that maps the partition key and associated data to a specific shard. Specifically, an MD5 hash
     * function is used to map partition keys to 128-bit integer values and to map associated data records to shards. As
     * a result of this hashing mechanism, all data records with the same partition key map to the same shard within the
     * stream.
```

So, feel free to raise a Pull Request with the fix!
Fortunately we have some time until this Friday release.

Thanks
