### ISSUE TITLE
How to use KCL/KPL

### ISSUE THREAD

**Issue by akefirad** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#117]
I'm not sure if it's a bug or wrong configuration in my application.
So my understanding is that if I enable KCL/KPL feature, spring cloud stream is gonna use KCL to coordinate consumers in the group. (Is my understanding correct?).
The problem is that when I enable the feature, I still see spring cloud stream asking for access to lock registry and metadata store tables. And also KCL is asking to have access to the `my-foo-application` table (I'm not sure where it reads the value, but I set it in `spring.application.name`).  
I couldn't find any documents on how to properly use spring cloud stream with KCL/KPL. Can someone help me with this?

**Comment by artembilan** [comment]
While I agree that it is a bug to try to connect into lock registry and metadata store tables, it is still valid to attempt to connect to the `my-foo-application` table, because KCL is still using a DynamoDB for checkpoint management.
It is also using a CloudWatch service for instances coordination.

I don't think it is this project responsibility to document how to configure AWS account to work with KCL. It is really covered by AWS which we fully rely on.

So, I'll fix condition for beans to avoid extra AWS objects creation when we definitely don't need them, but docs issue is definitely out of this project scope.

Thanks for understanding.

**Comment by akefirad** [comment]
Thanks for the reply.
> don't think it is this project responsibility to document how to configure AWS account to work with KCL. It is really covered by AWS which we fully rely on.

I think there's a misunderstanding here. I was asking for some information on how to properly use spring cloud stream with KCL/KPL.

**Comment by artembilan** [comment]
Well, you are OK so far. Only the problem that we have that but you are facing.
And it will be fixed soon enough.

Or do you see something else which really should be documented on our side?

Thanks

**Comment by akefirad** [comment]
Not sure, maybe it's because I just started working with the KCL/KPL. So just to recap everything is fine (even though spring tries to access its own tables and stuff, and you're gonna take care of it?). Just two quick follow up questions: How can I specify the table name for KCL via Spring Boot properties? And also after the fix I can remove/delete spring specific tables (lock registry and metadata)? Is my understanding correct?

**Comment by artembilan** [comment]
Your understanding is correct. And if you are going to use only KCL mode, those "Spring-specific" tables can be removed.
Or vise-versa in case of non-KCL mode.

The DynamoDB table for KCL is based on the `group` property for binding. See Spring Cloud Stream docs for more info: https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.0.RELEASE/reference/html/spring-cloud-stream.html#consumer-groups

**Comment by ywilkof** [comment]
Currently when using KCL\KCP support it is impossible to set the KinesisClientLibConfiguration properties, as it is not injected and initialized during creation. One consequence is that one cannot change the table name. Consumer group name name must align with the (possibly) auto generated name of the dynamo db table, as pointed out in this thread. Another consequence is that one cannot update many of the properties, and instead only the client's defaults are used. This makes the KCL\KCP adapter hard to use, as one loses a lot of the control that one could achieve by using it directly. Are there any plans to allow injecting this as bean or allow setting extra client library properties?
Thanks.

**Comment by artembilan** [comment]
OK! I see your point, @ywilkof !

Let me to expose a `KinesisClientLibConfiguration` ctor on the `KclMessageDrivenChannelAdapter` and then will be able to expose it as a conditional bean over here in the binder implementation and after that you could create your own bean overriding our possible defaults.

Stay tuned!

**Comment by artembilan** [comment]
@ywilkof ,

please, find the fix in the commit linked to this issue.

So, you can configure now a `KinesisClientLibConfiguration` for an appropriate `stream` and `applicationName`.
The binder then will try to find that bean from a destination on the binding when it create a KCL consumer.
If no bean for a stream, fallback to the default behavior.
