### ISSUE TITLE
How to stop trying to connect to kinesis on startup

### ISSUE THREAD

**Issue by lukebellamy053** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#127]
We're having a problem with our spring boot project where we only want to connect to kinesis if a given property is set. We've tried fixing this by replacing the beans and by using the test library but none of these are desirable solutions.

Is there some built-in way or could something be added to make it easier to switch kinesis on and off using a property?

The reason for this is that we don't want to have to start localstack on our machines unless its necessary since the consumer is only a small part of the overall application

Thanks

**Comment by artembilan** [comment]
Are you sure that the story is really about connecting to Kinesis service, not something more generics, e.g. security for AWS account?

Consider to have this on test `@Configuration` class:

```
@EnableAutoConfiguration(exclude = {
			ContextResourceLoaderAutoConfiguration.class,
			ContextStackAutoConfiguration.class })
```

**Comment by lukebellamy053** [comment]
@artembilan I think you've missed the point of my question but I don't think i was very clear. We wanted the option of turning the consumer on or off while developing locally. We use localstack for kinesis locally and not a real AWS instance so it has nothing to do with security or permissions etc.

We did manage to achieve this in the end and for anyone else with the same problem the code below is how we did it (note that capacity.consumer.enabled is the property flag that turns the consumer on or off):

```
@Component
@ConditionalOnExpression("!${capacity.consumer.enabled}")
class DummyBinder implements Binder<MessageChannel, ConsumerProperties, ProducerProperties> {

	@Override
	public Binding<MessageChannel> bindConsumer(String name, String group,
			MessageChannel inboundBindTarget, ConsumerProperties properties) {
		return new DummyBinding();
	}

	/**
	 * Registers a single subscriber to the channel, that enqueues messages for later
	 * retrieval and assertion in tests.
	 */
	@Override
	public Binding<MessageChannel> bindProducer(String name,
			MessageChannel outboundBindTarget, ProducerProperties properties) {
		return new DummyBinding();
	}

	private static final class DummyBinding implements Binding<MessageChannel> {

		@Override
		public void unbind() {
		}

	}

}

```
