### ISSUE TITLE
Messages being consumed on the same thread

### ISSUE THREAD

**Issue by toppratyush007** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#131]
I have multiple channels defined under an interface consuming from same destination under different consumer groups
```
public interface Channels {

  @Input
  SubscribableChannel x();

  @Input
  SubscribableChannel y();

  @Input
  SubscribableChannel z();

}
```

But all of the above channels , when using 
```
@StreamListener
```
are being consumed on the same thread, and one thread ,
```
esis-consumer-1
```
if it takes long, causes all the other work streams to be stalled. Anything that can be configured for multiple threads ?

**Comment by artembilan** [comment]
Closed in favor of question on the forums/gitter.

GH issues are not for questions.
