### ISSUE TITLE
Multiple Consumers processing the same message

### ISSUE THREAD

**Issue by pingrulez** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#132]
Environment:
AWS:
    Amazon Stream: 1
    Amazon Shards: 10
    Kubernetes Consumer Pods: 3

Spring:
    Dockerized Spring Boot Running in Amazon EKS
    spring-cloud-stream-3.0.1.RELEASE.jar
    spring-cloud-stream-binder-kinesis-2.0.1.RELEASE.jar
    amazon-kinesis-client-1.13.0.jar
    
App Config:
    spring.cloud.stream.bindings.input.destination=dev-incomingHeartbeatExpirationStream
    spring.cloud.stream.bindings.input.group=outageService
    spring.cloud.stream.bindings.input.consumer.listenerMode=batch
    spring.cloud.stream.default.consumer.headerMode=none

Issue:

Once all 3 PODS (Spring Boot App) are RUNNING, they each consume the same message.

Please let me know what additional information you might need me to provide to resolve this situation.

Appreciate the help!!!!!!!!

<img width="2919" alt="duplicateMessages" src="https://user-images.githubusercontent.com/12105570/79460528-f3452780-7fc2-11ea-8ad1-4c28c7174b73.png">

**Comment by pingrulez** [comment]
I added the following property and it now seems only one consumer is processing the message as expected.

I may have passed up documentation that this would also prevent multiple consumers processing the same message.  Would you be able to confirm this is the correct parameter and behavior?

spring.cloud.stream.kinesis.binder.kpl-kcl-enabled=true

Thank you again!
Kevin Berggren

**Comment by artembilan** [comment]
Your consumer instances with the same group may read the same record from the same stream and shard only in case if you don't use a shared `MetadataStore`.
It has to be DynamoDb by default. And that is one which is used for KCL as well.

On the other hand, if you are sure that all your instances uses the same DynamoDb table for checkpointing, please, let us know how it works if you use `spring.cloud.stream.bindings.input.consumer.listenerMode=record`.

**Comment by pingrulez** [comment]
Yes, in both cases (kpl-kcl-enabled = true or false) we are using DynmoDb as the shared MetadataStore.

Before making changes to support consuming byte[] as opposed to a List<byte[]>, is there a higher probability for processing duplicates in batch mode?

**Comment by artembilan** [comment]
> Before making changes to support consuming byte[] 

I don't force you to do such a critical change in your business logic - just for sake of experiment to be sure that behavior is the same or not.

There is also a `LockRegistry` which has to be shared as well. And by default it is based on the same DymanoDb.
A default table is `SpringIntegrationLockRegistry`. Please, confirm that only one instance of your consumers has an item in the table for the same `group/stream/shard`.
This is the way how we try to ensure that only one instance in the consumer group is an exclusive owner of the shard to consume at some specific moment.

**Comment by pingrulez** [comment]
I have confirmed that only one instance of the consumers has an item in the table.
Thank you for you help!

**Comment by ravimajji** [comment]
Is there a way to override the default DDB table name SpringIntegrationLockRegistry. We have issues accessing this table because of custom auth policies of the org.
