### ISSUE TITLE
Replace describeStream with listStream 

### ISSUE THREAD

**Issue by mwesox** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#134]
We're having big issues with our Kinesis-Services. 
Services cant startp up due to `Got LimitExceededException when describing stream`. 
The reason is here, that Spring Kinesis Binder uses describeStream API to list all the shards (see link below) . AWS recommends to use listShards API for this purpose, which has highe limits. 

https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/master/spring-cloud-stream-binder-kinesis/src/main/java/org/springframework/cloud/stream/binder/kinesis/provisioning/KinesisStreamProvisioner.java#L119

**Comment by artembilan** [comment]
Sounds reasonable.

Feel free to go ahead with a PR as a contribution!

**Comment by mwesox** [comment]
hi @artembilan, 

I've implemented it. How can I push the PR? I'm getting a 403 - permission denied, when pushing the PR.  

I already signed the CLA. Does it take a while, until I get access ? 

Cheers

**Comment by artembilan** [comment]
Thank you @mwesox , for the effort!

I think you need to fork this project, create a top-level branch from the `origin/master`, push it into your `origin` and then open a PR against that branch.
See more details over here: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc

**Comment by mwesox** [comment]
Ahh thanks for the hint. Sorry, my first time ;) ... Here is the PR: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/pull/135
