### ISSUE TITLE
Kinesis consumer group - all instances are getting the same message

### ISSUE THREAD

**Issue by saverineni** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#136]
My Configuration:

spring.application.name: my-application
spring.cloud.stream.kinesis.binder.kpl-kcl-enabled: true
spring.cloud.stream.kinesis.binder.locks.table: my-application-lockregistry
spring.cloud.stream.kinesis.binder.checkpoint.table: my-application-metadata-store
spring.cloud.stream.kinesis.bindings.event-log-stream.consumer.shardIteratorType: TRIM_HORIZON

spring.cloud.stream.kinesis.bindings.event-log-stream.group: "my-group-name"
spring.cloud.stream.kinesis.bindings.event-log-stream.destination: "stream-name-1"

dependencies:
spring-cloud-stream-binder-kinesis:jar:1.2.1
aws-sdk-java-dynamodb:jar:1.11.415
spring-cloud-stream:jar:2.1.2

issue:

I have started 2 instances of my microservice within the same consumer group, both with above configuration. when i send a message to kinesis stream both instances are receiving the same message, I was expecting only one instance to get invoked.

As soon as i start an instance it automatically created dynamodb lock and metadata store tables (as mentioned in the configuration) in dynamodb . Both the tables are empty even after the message is consumed by both the instances.

For a kinesis message i want only 1 of the 2 instances to be invoked not both.

questions:

1) Are my dependency versions correct to implement what I am expecting?

2) is there anything wrong with my YAML configuration, I tweaked and tested my YAML changing the bindings without success.

your help is much appreciated.

**Comment by saverineni** [comment]
@artembilan I have gone many similar questions but couldn't figure out what i am missing here.

**Comment by artembilan** [comment]
These are wrong:
```
spring.cloud.stream.kinesis.bindings.event-log-stream.group: "my-group-name"
spring.cloud.stream.kinesis.bindings.event-log-stream.destination: "stream-name-1"
```
they are not Kinesis-specific properties. 
Should be just like this:
```
spring.cloud.stream.bindings.event-log-stream.group: my-group-name
spring.cloud.stream.bindings.event-log-stream.destination: stream-name-1
```

See docs on the matter: https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.4.RELEASE/reference/html/spring-cloud-stream.html#_common_binding_properties
