### ISSUE TITLE
Release 2.0.2 planned?

### ISSUE THREAD

**Issue by Alien2150** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#142]
Hey guys, 

I am wondering if there is a release planned soon @artembilan? Especially looking for https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/issues/134

**Comment by artembilan** [comment]
Releasing today.
Thank you for heads up!

**Comment by Alien2150** [comment]
Thx so much @artembilan

**Comment by artembilan** [comment]
Fixed like this: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/releases/tag/v2.0.2.RELEASE
