### ISSUE TITLE
Add docs infrastructure

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#15]
As a developer, I'd like to add the docs infrastructure and the overview section for Kinesis binder.

**Acceptance:**
- Similar to Rabbit and Kafka, we would like to document producer and consumer properties and how it relates to overall binder configurations.
- It'd be useful to also have an architecture visual [similar to other binders](http://docs.spring.io/spring-cloud-stream/docs/Chelsea.SR2/reference/htmlsingle/index.html#_apache_kafka_binder_overview).

**Comment by artembilan** [comment]
The overall Docs infrastructure is added.
The rest of details will be added eventually, together with the features appearance.
