### ISSUE TITLE
`KinesisBinderHealthIndicator` thread safety problem

### ISSUE THREAD

**Issue by acm19** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#150]
While looking at the code I noticed `KinesisBinderHealthIndicator` uses `KinesisMessageChannelBinder#getStreamsInUse` which is not thread safe. I haven't experienced any issues with this but this could cause potential issues very hard to reproduce.

**Comment by artembilan** [comment]
Confirmed.

The `KinesisMessageChannelBinder.getStreamsInUse()` just returns an internal list as is, which could be modified at any point when we call `createProducerMessageHandler()` or `createConsumerEndpoint()`.

If you have a solution in mind, feel free to contribute it and we review & merge it shortly.

Thank you!
