### ISSUE TITLE
Unable to connect to Kinesis stream using Spring Cloud Stream Kinesis binder due to error java.lang.IllegalArgumentException: 'dynamoDBClient' must not be null

### ISSUE THREAD

**Issue by arvindkgs** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#152]
ERROR : java.lang.IllegalArgumentException: 'dynamoDBClient' must not be null

//Stream binding
     
    EnableBinding(DataStream.class)
    public class StreamsConfig {}

//Stream config

     public interface DataStream {
     
        String AUDIT_IN = "auditIn";

        @Input(AUDIT_IN)
        SubscribableChannel auditIn();
     }

//Stream Listener 

     @StreamListener(DataStream.AUDIT_IN)
        public void processAudit(finalAuditMessage auditMessage) {
         logger.info("Received audit message : {}", auditMessage);
         MDCUtil.setContext(auditMessage.getTenantId(), null, null);
         persistAuditMessage(auditMessage);
         MDCUtil.clearContext();
     }

Application.yaml

      cloud:
        aws:
          stack:
            auto: false
          region:
            static: us-west-2
          credentials:
            useDefaultAwsCredentialsChain: true

      management:
        context-path: /actuator
        security:
          enabled: false
          roles: ADMIN

        endpoint:
          metrics:
            enabled: true
          loggers:
            enabled: true
          health:
            show-details: always

        endpoints:
          web:
            exposure:
              include: "health,metrics,info,loggers"

        metrics:
          export:
            statsd:
              enabled: true
              flavor: telegraf
              host: telegraf-s.cluster-services.svc.cluster.local
              port: 8125
          tags:
            service: audit
            namespace: {{ .Release.Namespace }}

          distribution:
            percentiles:
              http:
                server:
                  requests: 0.5,0.9,0.99

            percentiles-histogram:
              http:
                server:
                  requests: true

      logging:
        level:
          org.hibernate.SQL: DEBUG
          org.hibernate.type.descriptor.sql.BasicBinder: TRACE

      spring:
        application:
          name: audit
        zipkin:
          enabled: false
        cloud:
          stream:
            bindings:
              auditIn:
                content-type: application/json
                destination: ***
                consumer:
                  describeStreamRetries: 10
                group: ***

            kinesis:
              binder:
                autoCreateStream: true
                autoAddShards: false
                kplKclEnabled: true

          vault:
            token: 00000000-0000-0000-0000-000000000000
            ssl:
              trust-store: ***
              trust-store-password: ***
            generic:
              enabled: false
            host: localhost
            port: 8200
            scheme: https
            connection:
              timeout: 5000
            read-timeout: 15000
            authentication: KUBERNETES
            kubernetes:
              role: owner
              kubernetes-path: kubernetes
              service-account-token-file: token
            kv:
              enabled: false
              backend: kv-v2
              application-name: configuration/mysql

        jpa:
          open-in-view: false

      audit:
        filter:
          block:
            methods: GET

Debug log : https://drive.google.com/file/d/1ACT_iYFP91r4XbSAqZPcNYt2Am2RhQf8/view?usp=sharing

pom.xml - https://drive.google.com/file/d/1kBEj6HqTQS5BgA7StaFZBEKfbLrpgSMR/view?usp=sharing

Using following jars
```
org.springframework.cloud:spring-cloud-stream-binder-kinesis:jar:2.0.0.RELEASE:compile
[INFO] |  +- com.amazonaws:amazon-kinesis-client:jar:1.13.0:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-cloudwatch:jar:1.11.655:compile
[INFO] |  |  \- com.google.protobuf:protobuf-java:jar:2.6.1:compile
[INFO] |  +- com.amazonaws:amazon-kinesis-producer:jar:0.14.0:compile
[INFO] |  |  \- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  +- org.springframework.integration:spring-integration-aws:jar:2.3.0.RELEASE:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-aws-core:jar:2.2.0.RELEASE:compile
[INFO] |  |  |  +- com.amazonaws:aws-java-sdk-ec2:jar:1.11.415:compile
[INFO] |  |  |  \- com.amazonaws:aws-java-sdk-cloudformation:jar:1.11.415:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-aws-messaging:jar:2.2.0.RELEASE:runtime
[INFO] |  |  |  +- com.amazonaws:aws-java-sdk-sns:jar:1.11.415:runtime
[INFO] |  |  |  \- com.amazonaws:aws-java-sdk-sqs:jar:1.11.415:runtime
[INFO] |  |  +- org.springframework.integration:spring-integration-file:jar:5.2.2.RELEASE:runtime
[INFO] |  |  \- org.springframework.integration:spring-integration-http:jar:5.2.2.RELEASE:runtime
[INFO] |  +- org.springframework.cloud:spring-cloud-starter-aws:jar:2.2.0.RELEASE:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-aws-context:jar:2.2.0.RELEASE:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-aws-autoconfigure:jar:2.2.0.RELEASE:compile
[INFO] |  |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-dynamodb:jar:1.11.415:compile
[INFO] |  |  \- com.amazonaws:aws-java-sdk-s3:jar:1.11.415:compile
[INFO] |  |     \- com.amazonaws:aws-java-sdk-kms:jar:1.11.415:compile
[INFO] |  +- com.amazonaws:dynamodb-lock-client:jar:1.1.0:compile
[INFO] |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.12:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-kinesis:jar:1.11.415:compile
[INFO] |  \- com.amazonaws:dynamodb-streams-kinesis-adapter:jar:1.5.0:compile
```

**Comment by artembilan** [comment]
> org.springframework.cloud:spring-cloud-stream-binder-kinesis:jar:2.0.0.RELEASE:compile

Let's see first of all how it works for you if you upgrade your project to the latest `2.0.4.RELEASE` version!

**Comment by arvindkgs** [comment]
Same error. Using -
```
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kinesis</artifactId>
            <version>2.0.4.RELEASE</version>
        </dependency>
<dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-sts</artifactId>
            <version>1.11.600</version>
        </dependency>
```

**Comment by arvindkgs** [comment]
Sorry my bad! I was creating a DynamoDBClient bean which returned null.
