### ISSUE TITLE
Using spring cloud stream binder without Spring Boot

### ISSUE THREAD

**Issue by hanymorcos** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#155]
We don't use Spring Boot on our project.  I'm using a DispatcherServlet to create the Application Context and feed spring.xml configuration through that.  I'm trying to get Spring Cloud to work without using spring boot.  I'm not sure what it's not finding the processor, channelfactory, and GenericApplication Context. 

Thanks.
H

Error creating bean with name 'kinesis': Unsatisfied dependency expressed through field 'processor'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.cloud.stream.messaging.Processor': Unsatisfied dependency expressed through field 'bindingTargetFactories'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'channelFactory': Unsatisfied dependency expressed through field 'context'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.context.support.GenericApplicationContext' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

**Comment by garyrussell** [comment]
You cannot - spring-cloud-stream requires Spring Boot.
