### ISSUE TITLE
Any ETA on latest Spring Cloud AWS 2.3 support?

### ISSUE THREAD

**Issue by edgarRSV4** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#157]
Hey! Was just wondering if adding support for the Spring Cloud AWS 2.3 was already in your roadmap to have an ETA https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/master/pom.xml#L20.

https://spring.io/blog/2021/03/17/spring-cloud-aws-2-3-is-now-available

**Comment by artembilan** [comment]
Sure! We can do that ASAP. When this is fixed: https://github.com/spring-projects/spring-integration-aws/issues/193, we are good to move Kinesis binder to version `2.2`  and therefore Spring AWS `2.3`.

The contribution is welcome!

**Comment by edgarRSV4** [comment]
Will take a look and see if I manage to contribute, thanks @artembilan !

**Comment by artembilan** [comment]
I have just started version `2.2` for this project.
Feel free to PR an upgrade to SC-AWS `2.3` and probably all the rest, including recently upgraded SI-AWS `2.5`
