### ISSUE TITLE
Unable to connect multiple kinesis streams as input in one MS 

### ISSUE THREAD

**Issue by amarsingh12345** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#159]
@artembilan  As there is only one input parameter so unable to configure multiple inputs of same type as kinesis in application yml .

spring.cloud.stream:
      bindings:
        input:
          group:

**Comment by artembilan** [comment]
I'm not sure what is the problem you see with this project, so I'm closing this as invalid and forwarding you to StackOverflow.
Please, come back to us from there with much more info.
Meanwhile you learn configuration properties for bindings: https://docs.spring.io/spring-cloud-stream/docs/3.1.2/reference/html/spring-cloud-stream.html#binding-properties
