### ISSUE TITLE
Add updateShardCount = true/false consumer/producer property

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#16]
See more context in the https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/pull/5#discussion_r130678162

**Comment by JacobASeverson** [comment]
A few questions:

1. Should there be a property `minShardCount` for specifying minimum shards (similar to the Kafka binder's `spring.cloud.stream.kafka.binder.minPartitionCount`)? 
2. Should the binder only scale up the number of shards during update, or should it also attempt to scale down when appropriate?

**Comment by artembilan** [comment]
Thank you, @JacobASeverson , for coming back to us!

I talked to @sobychacko yesterday on the matter and we decided to follow with the Kafka Binder approach. To be consistent.
So, If `autoAddShards == true` and requested count is more then existing size, we increase the number of shards. Otherwise just ignore the requested.

I don't see reason in other options. They don't bring too much value and can be added on demand.

**Comment by JacobASeverson** [comment]
Apologies for the wait, I'm working on finishing up a PR to close this.

Just curious, is there a timeline for a release of Spring Integration AWS? I noticed you added configurable waiting on DynamoDB tables in https://github.com/spring-projects/spring-integration-aws/issues/77 which would solve the errors I'm seeing frequently on startup.

**Comment by artembilan** [comment]
Welcome back @JacobASeverson !

No problem about waiting!

Well, I'm going to release `SI-AWS-1.1.0.RC1` today. There is some open question about concurrent consumers in the same consuming group and same shard. I doesn't work as expected if listener takes some time to handle the record. So, we may have duplicates in several instances of our application.

I'm considering to re-write the logic in the `KinesisMessageDrivenChannelAdapter` to something like leader election. But that's already for the next version `2.0`. Right now I only think to checkpoint offset before sending to the listener. and do that only for the `batch` mode.

**Comment by JacobASeverson** [comment]
Interesting, thanks for the update! Just out of curiosity, how come you implemented the kinesis integration on top of the kinesis sdk instead of the kinesis client lbrary?

**Comment by artembilan** [comment]
Well, hard to answer to this question already.
It is confidential information from some time ago...

**Comment by JacobASeverson** [comment]
Ok no worries, was just curious 😃

**Comment by JacobASeverson** [comment]
Opened https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/pull/24 to address this.

**Comment by artembilan** [comment]
:+1: looking forward to overview it in the morning!
