### ISSUE TITLE
Using snapshot versions without an official mvn release?

### ISSUE THREAD

**Issue by edgarRSV4** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#160]
This is not so project specific but was just wondering...

Which is the best approach for using Spring related releases without waiting for the official Maven release? Looking forward to use the latest 2.2.0-SNAPSHOT (not only this one but also integration and other libs that may be required to be in-sync).

**Comment by artembilan** [comment]
Such a question is really very general for Spring ecosystem at all, not just particularly for this project.
So, better to come to us with questions like this on StackOverflow.

To test our snapshots in your project, you should add this repository into your Maven config:
```
				<repository>
					<id>spring-snapshots</id>
					<name>Spring Snapshots</name>
					<url>https://repo.spring.io/libs-snapshot</url>
				</repository>
```
