### ISSUE TITLE
Spring cloud stream kinesis binder with Enhanced fanout

### ISSUE THREAD

**Issue by nag-nagaruru** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#166]
By default all the AWS kinesis Consumer application share the 2 MB per second read limit across all the consumers. With Kinesis enhanced fan-out each consumer will have it's own 2 MB read limit per shard instead of sharing across all the consumers. For enhanced fanout , we need to make use of KCL 2.x versions.

Is there any plan for that upgrade for Spring cloud stream library to make use of Kinesis enhances fan out ?

**Comment by sabbyanandan** [comment]
Hi, @nag-nagaruru. It depends on https://github.com/spring-cloud/spring-cloud-aws/issues/267, an upstream project's AWS SDK 2.0 compatibility effort. Please share your suggestion or vote on this community-driven project, so it has been accounted for and prioritized.  

And, for questions like this, please stick with StackOverflow in the future.
