### ISSUE TITLE
Not Able to Connect Kinesis Stream in PROD environment

### ISSUE THREAD

**Issue by devarajan81** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#170]
Hi Team,

I am able to consume data from Kinesis as listener in lower environments, but unable to connect Kinesis stream in PROD environment.

Added the Proxy configuration changes and Firewall is allowed to invoke the kinesis Stream URL : kinesis.us-east-1.amazonaws.com/3.227.250.191.

But still getting the below error in PROD environment.

**org.apache.http.conn.ConnectTimeoutException: Connect to kinesis.us-east-1.amazonaws.com:443 [kinesis.us-east-1.amazonaws.com/3.227.250.191] failed: connect timed out**

Regards,
Deva

**Comment by artembilan** [comment]
Sorry, I don't see what the problem you point out exactly in this project.
Probably better to chat to broader AWS community: over some public forum or directly via their support.

Unfortunately there is nothing what this Spring library can do for you to mitigate your connection problem.

Closed as `Invalid`
