### ISSUE TITLE
Iterator Expiring 

### ISSUE THREAD

**Issue by ShivaKumarReddyVarkala** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#171]
50e776f32ace 07:05:22.079 [-kinesis-consumer-1] DEBUG com.amazonaws.request[1] - Received error response: com.amazonaws.services.kinesis.model.ExpiredIteratorException: Iterator expired. The iterator was created at time Sun Oct 10 05:17:11 UTC 2021 while right now it is Sun Oct 10 07:05:22 UTC 2021 which is further in the future than the tolerated delay of 300000 milliseconds. (Service: AmazonKinesis; Status Code: 400; Error Code: ExpiredIteratorException; Request ID: df4650ed-d137-e3cc-869a-c21f3276ffd1; Proxy: null)

Config: 

  cloud:
    stream:
      bindings:
        input:
          consumer:
            auto-startup: ${}
          destination: ${}
          group: ${}
          content-type: text/plain
      kinesis:
        binder:
          checkpoint:
            table: ${}
          locks:
            table: ${}
        bindings:
          input:
            consumer:
              startTimeout: 60000
              listenerMode: record
              checkpointMode: periodic
              recordsLimit: 1000

**Comment by artembilan** [comment]
Closed as "No feedback from reporter"
