### ISSUE TITLE
Add DynamoDBMetadataStore support

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#18]
Since `DynamoDBMetadataStore` is already available in the SI-AWS, that feels organic to go ahead and add it into the `KinesisBinder`. 

The `MetadataStore` bean (`kinesisCheckpointStore` is the name) must follow auto-configuration convention with the `DynamoDBMetadataStore` as default one, but end-user can provide his own impl overriding the default. This way we can easily test against local Kinesalite but don't collide with the same port for the Dynalite.

**Comment by oatesp** [comment]
This looks like it will be required to enable checkpointing in applications so they can recover after failure.

No idea how to get started on it though...

**Comment by artembilan** [comment]
@oatesp ,

thank you for taking a look into this issue and for wishes to contribute!

So, frankly the "checkpointing" is there already, but it is done against in-memory `SimpleMetadataStore`. See `KinesisMessageDrivenChannelAdapter`:
```
private MetadataStore checkpointStore = new SimpleMetadataStore();
```
The idea with this ticket to add conditional `DynamoDBMetadataStore` `@Bean` definition to the `KinesisBinderConfiguration` and inject it into the `KinesisMessageChannelBinder` with subsequent delegation to the `KinesisMessageDrivenChannelAdapter`.

That's all.

**Comment by oatesp** [comment]
I think I've coded this up now, just having a bit of trouble around the auto creation of the Dynamo table, I'm also not 100% happy with how I've implemented the properties.

I'll try to PR it tomorrow to see what you guys think.

Thanks,
