### ISSUE TITLE
Update Spring Cloud AWS dependency in Kinesis binder

### ISSUE THREAD

**Issue by rbraeunlich** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#181]
Hi everyone,

the Kinesis binder still depends on Spring Cloud AWS 2.4.0. As I can see the 4.0.0 version of your projects all depend on the latest Spring version (6.0.0). Therefore, the Kinesis binder should use the latest Spring Cloud AWS version, which is 3.0.0-M3

Cheers,
Ronny

**Comment by artembilan** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/commit/fba430a4b03fb229fcdc05fef42e356ce7f3a36d
