### ISSUE TITLE
Break dependence on KafkaAutoConfiguration for Kinesis binder

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#183]
Do the same thing to the Kinesis binder that was done for the other Kafka binders in spring-cloud/spring-cloud-stream#2362 

- requested [here](https://github.com/spring-cloud/spring-cloud-stream/pull/2362#pullrequestreview-952309421)

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/commit/fba430a4b03fb229fcdc05fef42e356ce7f3a36d
