### ISSUE TITLE
Dynamic partition key

### ISSUE THREAD

**Issue by KanikaKandasamy** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#184]
Is there a way to set partition key dynamically in the current version using Suppiler/Consumer?

The partition key is always directed to 0 in my case.

**Comment by artembilan** [comment]
Closed in favor of: https://stackoverflow.com/questions/75217469/how-to-set-dynamic-partition-key-in-spring-cloud-aws-kinesis-binder.

The GH issues are not for asking questions.
