### ISSUE TITLE
Implement Micrometer trace id propagation from producer to consumer to support Observability tracing requirements

### ISSUE THREAD

**Issue by kabennett** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#185]
Please fix the Kinesis binder so that Micrometer trace ids are propagated from a producer to a consumer. 

Per @artembilan on [this](https://stackoverflow.com/questions/75102667/propagating-trace-ids-across-http-rest-and-kinesis-messaging-service-boundaries/75114280?noredirect=1#75114280) stackoverflow post:

_The Kinesis Binder will need to be fixed. Even if we got an observation context via that customizer, we cannot extract current trace: it is done a bit later by respective EmbeddedHeadersChannelInterceptor. And channel is already a PRODUCER kind: it does not care what we have in the headers, but it set new value. So, "unembedding" headers must happen exactly in the Kinesis Consumer endpoint where we set a trace as a CONSUMER and this one is already about extracting context from headers._

Another [GH issue](https://github.com/spring-cloud/spring-cloud-stream/issues/2639) was opened related to this issue and may need to be correlated with this one.

**Comment by artembilan** [comment]
A title of the issue is a bit misleading with its description, but I can address both concerns in one commit:

1. We need to move embedded headers logic into Kinesis channel adapters instead of the `EmbeddedHeadersChannelInterceptor`
2. We need to expose `enableObservation` option for Kinesis Binder as it is done for other binders.

**Comment by artembilan** [comment]
Implemented as https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/commit/bf102527a3866f0f754d73c09d638c181b13da06.
Will be available in the next `4.0.0`. Not sure when though...
