### ISSUE TITLE
AWS Kinesis binder fails to  consume messages as per the event published order

### ISSUE THREAD

**Issue by kamalakannanvkp** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#191]
**In what version(s) of Spring Cloud Stream Binder for AWS Kinesis are you seeing this issue?**

Please find the versions used as part of the current setup : 

- org.springframework.cloud:spring-cloud-stream-binder-kinesis:2.2.0
- org.springframework.integration:spring-integration-aws:2.5.4

**Describe the bug**

We have a micro-service publishing the messages to the aws kinesis stream (4 shards) , and the downstream system consumes the same for the processing.

We noticed the events sent from the publisher are stored in the right order at the AWS data streams. However the consumer , _fails to consume the events in the same published order_.

**To Reproduce**

2 Micro service , 1 for publisher and 1 for consumer to re-create the issue.

**Expected behavior**

The expected behaviour would be is to  : process the events from the kinesis binder in the same order as stored in the AWS data streams.

**Documents on the issue**

we have captured the events and their publish time at the Kinesis Streams , which could be seen from the below screenshots 

Events published from Service A | Events processed in Service B | Ordered processing ? |   | Kinesis received time stamp |   | Service B : received timestmap
-- | -- | -- | -- | -- | -- | --
4e547416-e2a6-11ed-94a6-8a573b12d9b5 | 4e547416-e2a6-11ed-94a6-8a573b12d9b5 | TRUE |   | April 26, 2023 at 12:49:34  |   | 2023-04-26T12:49:34.515
4e4fabb6-e2a6-11ed-94a6-8a573b12d9b5 | 4e4faf6c-e2a6-11ed-94a6-8a573b12d9b5 | **FALSE** |   | April 26, 2023 at 12:49:37  |   | 2023-04-26T12:49:43.540
4e4faf6c-e2a6-11ed-94a6-8a573b12d9b5 | 4e4fabb6-e2a6-11ed-94a6-8a573b12d9b5 | **FALSE** |   | April 26, 2023 at 12:49:41  |   | 2023-04-26T12:49:42.582
4e4fb278-e2a6-11ed-94a6-8a573b12d9b5 | 4e4fb278-e2a6-11ed-94a6-8a573b12d9b5 | TRUE |   | April 26, 2023 at 12:49:45  |   | 2023-04-26T12:49:47.554

_Find below the respective screengrab associated with the above table data's._

**KDS Events received**

<img width="950" alt="1" src="https://user-images.githubusercontent.com/8424867/236181521-e957d5e9-9fd8-4d11-94c1-2d4a6b5f4d1b.png">
<img width="932" alt="2" src="https://user-images.githubusercontent.com/8424867/236181548-46a994c5-86e0-4d78-a72f-aa2449434514.png">
<img width="950" alt="3" src="https://user-images.githubusercontent.com/8424867/236181565-daa3f877-36c9-4791-b79d-44cfa4305a3a.png">
<img width="948" alt="4" src="https://user-images.githubusercontent.com/8424867/236181582-a6b373a6-349a-450a-ba6f-e3cc48a0870d.png">

**Events processed in the service B with timestamp**

<img width="671" alt="event-received" src="https://user-images.githubusercontent.com/8424867/236207001-519ae1fb-c482-416c-a06a-8dcf358c13ee.png">

**Comment by artembilan** [comment]
I'm not sure what that info you are sharing, but my best guess that your events are placed into different shards of the stream. 
And AWS Kinesis ensures ordering only withing one shard.
On the consumer side every shard is processed in its own thread. 
Therefore its really expected that data from different shards might be consumed not in order it was produced.

Does it make sense?

**Comment by kamalakannanvkp** [comment]
thanks @artembilan  and yes you are right , we have 4 shards and the data is distributed across those shards.

**Comment by artembilan** [comment]
So? Is question solved?
Can we close this issue as "No issue"?

**Comment by kamalakannanvkp** [comment]
thanks @artembilan  , This issue can be closed.
