### ISSUE TITLE
Message headers getting appended in the data 

### ISSUE THREAD

**Issue by piratezoro** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#200]
Using spring cloud stream AWS kinesis binder, for consuming and producing events across kinesis streams :

Recently migrated to version :- 4.0.0

Post migration we could see that all the events that get's persist on the stream having headers appended onto the data.

Example:
?{"@class":"java.util.HashMap","contentType":"application/json"}{"id":"HeaderIssue01"}

Expected which was the case with the older version : 2.0.4.RELEASE
{"id":"HeaderIssue01"}

Our previously used version[ 2.0.4.RELEASE] did not have the headers appended. We could see LegacyEmbeddedHeadersSupportBytesMessageMapper adding header data into the byte buffer.

As all our consumers will be impacted due to this change is there a way to disable it by any property or any alternate solution.

**Comment by artembilan** [comment]
Not clear what you are asking: to not have headers embedded at all, or have them like it was in the previous version.

For the first use-case you just need to have an `spring.cloud.stream.kinesis.bindings.<bindingTarget>.producer.embed-headers = false` property.

Or use `spring.cloud.stream.kinesis.binder.legacy-embedded-headers-format = true` to use same embedding format as before.
