### ISSUE TITLE
Allow to configure the aws endpoint to improve test and development experience

### ISSUE THREAD

**Issue by eddumelendez** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#202]
**In what version(s) of Spring Cloud Stream Binder for AWS Kinesis are you seeing this issue?**

4.0.0

**Describe the bug**

Allow to set the endpoint in AWS clients for [KinesisAsyncClient](https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/eb03d529d93dc0367e6a6a1a49abced4ca93d562/spring-cloud-stream-binder-kinesis/src/main/java/org/springframework/cloud/stream/binder/kinesis/config/KinesisBinderConfiguration.java#L100C2-L107C3), [DynamoDbAsyncClient](https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/eb03d529d93dc0367e6a6a1a49abced4ca93d562/spring-cloud-stream-binder-kinesis/src/main/java/org/springframework/cloud/stream/binder/kinesis/config/KinesisBinderConfiguration.java#L116-L126) and [CloudWatchAsyncClient](https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/eb03d529d93dc0367e6a6a1a49abced4ca93d562/spring-cloud-stream-binder-kinesis/src/main/java/org/springframework/cloud/stream/binder/kinesis/config/KinesisBinderConfiguration.java#L193-L203) via configuration properties. This will allow to use `@DynamisPropertySource` in tests and local development with spring boot 3.1.

Currently, user should define the clients pointing to `LocalStackContainer` for testing.

`spring-cloud-aws` exposes a configuration property `spring.cloud.aws.endpoint` already, which can be considered for this implementation. To configure a client [this is the current implementation](https://github.com/awspring/spring-cloud-aws/blob/main/spring-cloud-aws-autoconfigure/src/main/java/io/awspring/cloud/autoconfigure/metrics/CloudWatchExportAutoConfiguration.java#L68-L73).

**To Reproduce**

N/A

**Expected behavior**

Define a test like this

```java
@Container
static LocalStackContainer localStack = new LocalStackContainer(DockerImageName.parse("localstack/localstack:2.2.0"));

@DynamicPropertySource
static void registerProperties(DynamicPropertyRegistry registry) {
    registry.add("spring.cloud.aws.endpoint", localStack::getEndpoint());
}
```

**Sample**

N/A

**Comment by artembilan** [comment]
Thank you!

This is fixed now the way you recommend and how it is auto-configured in Spring Cloud AWS.

**Comment by eddumelendez** [comment]
Thank you for fixing it so fast, @artembilan !
