### ISSUE TITLE
Upgrade Spring Cloud, Spring Cloud Stream, Spring Boot, Spring Cloud AWS to 2.0

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#21]

**Comment by artembilan** [comment]
I think we stick with the current SCSt `1.3.x` based line until the project is full of feature mentioned in the other issues. Then we will switch to the SCSt `2.0 M2` when it is ready and release our `1.0.0 M1`.

@JacobASeverson, @oatesp,

are you OK with the plan?
The general idea do not release this Binder against SCSt `1.x` at all.
