### ISSUE TITLE
Can't disable to send metric CloudWatch

### ISSUE THREAD

**Issue by Min3953** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#217]
**In what version(s) of Spring Cloud Stream Binder for AWS Kinesis are you seeing this issue?**

4.0.0

**Describe the bug**

I want to disable to send metric CloudWatch. I know that I can set metric config of KCL config to be NullMetricsFactory.
But I cannot set that with using kinesis binder. Is there the way that I want?

**Comment by artembilan** [comment]
Now since we have a `metricsLevel` option on the `KclMessageDrivenChannelAdapter`, it good to proceed here and expose it as a configuration property via `KinesisConsumerProperties`.
Thanks

**Comment by Min3953** [comment]
@artembilan 
Hello maintainer. Can I ask you when it will be released?
And, should I solve something? I don't know cause of build job failure. If failure occurred from my contribute, please tell me.

**Comment by Min3953** [comment]
@artembilan 
I set metrics level to NONE after this is released. But I observed metrics in CloudWatch same. Is there another route to send metrics?

**Comment by artembilan** [comment]
We need to know what are those metrics. Perhaps they are not related to Kinesis, or at least binder. What I mean it would be great if you can trace from those metrics what exactly component in your application emits them.

**Comment by Min3953** [comment]
I observed ProcessTask.{MetricName}
(like ProcessTask.DataBytesProcessed) include metric in this [link](https://docs.aws.amazon.com/streams/latest/dev/monitoring-with-kcl.html)

I attach my binding config
```yaml
            consumer:
              idle-between-polls: 250
              consumerBackoff: 100
              fan-out: true
              metrics-level: NONE
```

**Comment by Min3953** [comment]
@artembilan 
I found logic of sending metric of ProcessTask in aws kinesis client [link](https://github.com/awslabs/amazon-kinesis-client/blob/7f1f243676c7303975e9fd96d5138c367425a171/amazon-kinesis-client/src/main/java/software/amazon/kinesis/lifecycle/ProcessTask.java#L129)
It is written SUMMARY level hard.
if I want to disable sending all metrics, I should set MetricFactory to NullMetricsFactory.
Please point it out, if I'm wrong
