### ISSUE TITLE
How to retrieve UserRecordResult after a successful write to Kinesis stream

### ISSUE THREAD

**Issue by wlaw868** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#221]
In binder 2.x, we can retrieve the UserRecordResult object from the aws_serviceResult header in the output channel handler. However this is gone in binder 4.x, we are getting a PutRecordResponse instead. Even though it gives the shard Id and etc, it is missing the attempt as well as the delay which we use to measure the latency stat. Can you suggest workaround? Thanks!

**Comment by artembilan** [comment]
I see we have lost that info when we have migrated to AWS SDK v2.

Unfortunately, there is no workaround.
I see only as a fix something like:
```
class UserRecordResponse extedens KinesisResponse {
}
```
This way we would still keep the new contract for the:
```
protected abstract CompletableFuture<? extends AwsResponse> handleMessageToAws(Message<?> message,
			AwsRequest request);
```
and it will container all the data from the `UserRecordResult`.

If that makes sense, I'll look into the fix today and release new patch version.

Thank you for the pointer!

**Comment by artembilan** [comment]
However this has nothing to do with the Kinesis Binder.
So moving the issue into appropriate Spring Integration AWS repository: https://github.com/spring-projects/spring-integration-aws/issues/244

So, closed in favor of that.
