### ISSUE TITLE
recordsLimit or pollingMaxRecords not working

### ISSUE THREAD

**Issue by katyayanaanand** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#225]
I was using Java 8 and kinesis v2.2.0. In my consumer properties , I have set:
recordsLimit: 100
pollingMaxRecords: 100
listenerMode: batch
pollingIdleTime: 10000

and kplkclEnabled: true

pollingIdleTime is working but reordsLimit or pollingMaxRecords is not working so I'm not able to consume in assigned batch of 100.

**Comment by artembilan** [comment]
Can you tell us, please, more what is `kinesis v2.2.0` and what exactly version of `spring-cloud-stream-binder-aws-kinesis` you use?
The latest one is `4.0.4`. 
Consider to upgrade there: perhaps some your problems will disappear silently.

**Comment by katyayanaanand** [comment]
I will be more specific.
I am using following.
spring-cloud-stream-binder-kinesis:2.2.0
aws-java-sdk-kinesis:1.12.376
amazon-kinesis-client:1.14.9

Everything is working fine just that I want to know what properties to change to consume message in bulk.

**Comment by katyayanaanand** [comment]
I am not using fan out. It's regular Kinesis consumer only. I have restriction to use Java 8 only as of now, though I don't have any problem to upgrade kinesis-stream-binder. Can you suggest what properties I should change from above to restrict batch size?

**Comment by artembilan** [comment]
Don't use `kplkclEnabled: true`.
As I said before: the KCL does not come with that property in such an old version of Kensis binder.

**Comment by katyayanaanand** [comment]
java 8 issue :
As suggested by you, I tried to remove kplkclEnabled: true or set it as false, my consumer stopped polling. I can see events getting added in kinesis queue in data viewer and not getting consumed." I'm not sure how to debug this further.
Please suggest your views. That would be really helpful.

I also tried to upgrade the spring-cloud-stream-binder-kinesis version but my service was not reaching healthy state with java 17 and below dependencies :
        implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'io.micrometer:micrometer-registry-influx:1.9.13'
	implementation 'org.springframework.cloud:spring-cloud-stream:3.1.5'
	implementation 'org.springframework.integration:spring-integration-aws:3.0.8'
	implementation 'org.springframework.cloud:spring-cloud-stream-binder-kinesis:4.0.4'
	implementation 'com.amazonaws:aws-java-sdk-kinesis:1.12.376'
	implementation 'com.amazonaws:amazon-kinesis-client:1.14.9'

consumer properties (same in java8 and java 17):
recordsLimit: 100
pollingMaxRecords: 100
listenerMode: batch
pollingIdleTime: 10000

and kplkclEnabled: true

Please suggest what to change.

**Comment by katyayanaanand** [comment]
Java 8 :
As suggested, I tried with removing kplkclEnabled: true and also by setting kplkclEnabled: false. But my consumer stopped consuming. I can see events getting added in kinesis queue but my consumer class was not getting invoked and events also not getting consumed . I'm not sure if that's expected behaviour because consumer is consuming when I set, kplkclEnabled: true.

java 17 : 
I tried to upgrade my dependencies but my service is not reaching healthy state. Refer below : 
         'org.springframework.boot:spring-boot-starter-web'
	 'org.springframework.boot:spring-boot-starter-actuator'
	 'io.micrometer:micrometer-registry-influx:1.9.13'
	 'org.springframework.cloud:spring-cloud-stream:3.1.5'
	 'org.springframework.integration:spring-integration-aws:3.0.8'
	 'org.springframework.cloud:spring-cloud-stream-binder-kinesis:4.0.4'
	 'com.amazonaws:aws-java-sdk-kinesis:1.12.376'
	 'com.amazonaws:amazon-kinesis-client:1.14.9'

Please suggest changes in dependencies to make this work so that I can consume events in bulk.
consumer properties , I have set:
recordsLimit: 100
pollingMaxRecords: 100
listenerMode: batch
pollingIdleTime: 10000

and kplkclEnabled: true

**Comment by katyayanaanand** [comment]
Didn't find which dependency you referred with : The AWS SDK has to be 2.21.12

Java 17
springBootVersion = "3.0.13"
springCloudVersion = "2023.0.3"

I have updated other dependencies as you mentioned.

I used following dependencies :
        implementation 'org.springframework.cloud:spring-cloud-stream-binder-kinesis:4.0.5'
        implementation 'org.springframework.integration:spring-integration-aws:3.0.8'
        implementation 'com.amazonaws:aws-java-sdk-kinesis:1.12.376'
        implementation 'software.amazon.kinesis:amazon-kinesis-client:2.5.8'
        implementation "io.github.lognet:grpc-spring-boot-starter:4.9.1"
        
Error I got : 
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve org.springframework.cloud:spring-cloud-stream-binder-kinesis:4.0.5.
     Required by:
         project :
      > Could not resolve org.springframework.cloud:spring-cloud-stream-binder-kinesis:4.0.5.
         > Could not get resource 'https://repo.spring.io/release/org/springframework/cloud/spring-cloud-stream-binder-kinesis/4.0.5/spring-cloud-stream-binder-kinesis-4.0.5.pom'.
            > Could not GET 'https://repo.spring.io/release/org/springframework/cloud/spring-cloud-stream-binder-kinesis/4.0.5/spring-cloud-stream-binder-kinesis-4.0.5.pom'. Received status code 401 from server

**Comment by artembilan** [comment]
You must not use https://repo.spring.io/release. Rely on Maven Central instead.
You must not specify your own `aws-java-sdk-kinesis` dependency, but rather rely on the transitive one from the `spring-cloud-stream-binder-kinesis`.
The Kinesis Binder starting version `4.0` uses AWS SDK v2, therefore it is not compatible with the mentioned `aws-java-sdk-kinesis:1.12.376`.
I also don't think that the mentioned Spring Boot version (out of support as well) is compatible with that Spring Cloud version.
It might be better to rely on transitive one which is brought to us by Spring Cloud.

**Comment by artembilan** [comment]
There is no `spring-cloud-stream-binder-kinesis:4.0.5` version.
I've talked about Spring Cloud Stream: https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-stream/4.0.5
