### ISSUE TITLE
presence of embedded header mapper for batch processing results in consumer receiving an incorrect payload

### ISSUE THREAD

**Issue by kelseyh** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#227]
**In what version(s) of Spring Cloud Stream Binder for AWS Kinesis are you seeing this issue?**
4.0.4 

**Describe the bug**

Since upgrading to 4.x our consumer which is defined as `Consumer<List<String>>` no longer receives a list containing the json strings sent to kinesis, instead, the list contains jsonified `Message` objects. e.g. 
`{"payload": "base64 encoded payload", "headers": {...}` vs the expected `{"foo": "bar"}`

This is because version 4.x  adds a `LegacyEmbeddedHeadersMapper` to the Kcl/KinesisMessageDrivenChannelAdapter. When listenermode=batch this results in a `MessageBuilder` with a payload of `List<GenericMessage>` being sent to `performSend`. This makes sense as you need a way to pass the message headers along to the consumer (in our case we do not use embedded headers). Unfortunately, the converters do not deal with this correctly because they do not unwrap the items (i.e. perform message.getPayload() before conversion) in the list to match the consumers expected argument type which is `List<String>` and not `List<Message<String>>`  

**To Reproduce**
Configure a kinesis binder to have `consumer:listener-mode: batch`
Create a consumer `Consumer<List<String>>` 
Send some json on your kinesis channel e.g. `{"foo": "bar"}` 
Your consumer will then receive a List of jsonified Message objects

**Expected behavior**

The consumer should receive a List of json payloads.

**Comment by kelseyh** [comment]
We have tried setting `spring.cloud.stream.bindings.<binding_name>.consumer.header-mode=none` this does indeed remove the `LegacyEmbeddedHeadersMapper` unfortunately that just creates another problem on line 716 of `KclMessageDrivenChannelAdapter` which attempts to get the byte[] via `KclMessageDrivenChannelAdapter.this.converter.convert(r.data().array());` but `r.data()` returns a `HeapByteBufferR` which throws a `java.nio.ReadOnlyBufferException`

**Comment by kelseyh** [comment]
Thanks for the link for setting the header mode globally, I was looking in the kinesis binder docs previously. 

Just to clarify, are you saying that if an `embeddedHeaderMapper` is present then the only option for receiving messages in your consumer is to get a list of json representations of the `Message` when running in batch?

I tried to change my consumer to `Consumer<List<Message<String>>>` which I think accurately represents what's actually being passed to the integration layer from the `KclMessageDrivenChannelAdapter` but that just throws an exception in the JsonMessageConverter because the targetType is `String` despite the declaration `Message<String>.

**Comment by artembilan** [comment]
So, the logic of the `LegacyEmbeddedHeadersSupportBytesMessageMapper` is to return a `Message` with payload as `byte[]`, if headers have been embedded on the producer side and those embedded headers extracted.
Otherwise it is just plain: `message = (Message<?>) this.objectMapper.readValue(bytes, Object.class);`. Which may end up with a payload to be deserialized from its original type by Jackson.

In the end, before the batched message is sent to the channel we have content like: `Message<List<Message<Object>>>`.
Such a message is sent to the channel with some Spring Cloud Stream infrastructure.

Looking there with respective team.
However the `KinesisBinderFunctionalTests` say us that for the fine-grained batch payload it should be like:
```
@Bean
public Consumer<Message<List<Message<?>>>> eventConsumerBatchProcessingWithHeaders() {
```
This way I receive a single message where its payload is a list of messages and their payload is original produced string.

**Comment by artembilan** [comment]
So, turns out Spring Cloud Stream does not support (yet) that message structure for the batch - `Message<List<Message<?>>>`.
Therefore we have to provide `consumer.useNativeDecoding = true` option.
And our `Consumer` has to be only like that `Consumer<Message<List<Message<?>>>>`.

**Comment by kelseyh** [comment]
Ok, that makes sense because I'd tried `Consumer<Message<List<Message<?>>>` and it didn't work. 
Thanks

**Comment by artembilan** [comment]
For more visibility: https://github.com/spring-cloud/spring-cloud-function/issues/1202
