### ISSUE TITLE
Getting the ShardNumber and sequence number from AWSResponse when using KPLMessageHandler

### ISSUE THREAD

**Issue by siddharthjain210** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#229]
**In what version(s) of Spring Cloud Stream Binder for AWS Kinesis are you seeing this issue?**
4.0.0

**Describe the bug**
Not exactly a bug, but a query, 
When using KPLMessageHandler and sending PutRecord to KPL Message Handler, how do we get the response of published message record - shard id and sequence number. 

Within the KPL Message Handler, the output channel is marked as a NULL Channel, due to which we cannot hook any other success channel. 

Need to understand, if there is a capability other than output channel to record the AWS Response and do further actions. 

**Steps to reproduce the behavior**
kpl-kcl-enabled is true
using a spring cloud stream application, listening vial KCL and producing via KPL.   

**Expected behavior**
the AWS Response from Kinesis Producer PutRecord / PutRecords API shall be returned back to the application either in a success channel or a capability to register a delegate.

**Comment by artembilan** [comment]
I think what you are asking about that our hard-coded:
```
messageHandler.setOutputChannel(new NullChannel());
```
Makes sense.
I probably will introduce something like `binding.success` bean as a `PublishSubscribeChannel` which works as a `NullChannel` by default and target application can subscribe to that channel to consume those results.

**Comment by artembilan** [comment]
Or we will just follow whatever is there already in Kafka Binder: https://docs.spring.io/spring-cloud-stream/reference/kafka/kafka_tips.html#keeping-track-of-successful-sending-of-records-producing-in-kafka

**Comment by siddharthjain210** [comment]
Thank you Artem, exactly what was needed.
