### ISSUE TITLE
Spring Cloud Bus with AWS  kinesis

### ISSUE THREAD

**Issue by utpal416** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#28]
I am trying to integrate AWS kenisis with "spring-cloud-bus" instead of Rabit/Kafka so that I can refresh my all client with configuration changes from "Spring-Cloud-Server". I rebuild "spring-cloud-bus"  after putting "spring-cloud-stream-binder-aws-kinesis" dependencies  like below
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-stream-kinesis</artifactId>
	<version>1.0.0.BUILD-SNAPSHOT</version>
</dependency>
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-bus</artifactId>
	</dependency>
</dependencies>
```
Now in my own "spring config server" , I have put the below dependencies 
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-stream</artifactId>
</dependency>
<dependency>
         <groupId>org.springframework.cloud</groupId>
         <artifactId>spring-cloud-starter-stream-kinesis</artifactId>
         <version>1.0.0.BUILD-SNAPSHOT</version>
</dependency>
```
Now when I am trying launch my config server in my local machine and I am getting the below issue 

> Caused by: java.lang.IllegalStateException: There is not EC2 meta data available, because the application is not running in the EC2 environment. Region detection is only possible if the application is running on a EC2 instance

I need some help here to test it locally before putting that in EC2. Is there any help guide to test this binder locally ??

**Comment by artembilan** [comment]
If you are out of EC2, you have to configure `cloud.aws.region.static` explicitly. 

Please, consider to ask questions on StackOverflow. This is not a bug, nor feature request.
