### ISSUE TITLE
How could we change an interator type?

### ISSUE THREAD

**Issue by juneng603** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#30]
Hi,

I want to change a kinesis default iterator type(latest) to another, but I leave a question because it is difficult to find a sample code.

I'd appreciate it if you could tell me what to do.
Sharing it with sample codes would be great.

**Comment by artembilan** [comment]
Please, share more info what is the reason to go away of the `latest` and some real world sample of how and what would you like to see from our side to help you.

Thanks

**Comment by juneng603** [comment]
@artembilan 

More need to be concerned about this situation.
Think of it as a situation where a consumer-side's business is constantly changing and constantly improving. Of course, the deployments will continue to occur.

At this point, the data will continue to load into a kinesis. 
Support **at_sequence**  type iterator is essential for continuing to process the event without losing data.

**Comment by artembilan** [comment]
@juneng603,

Please, check the commit fixing this ticket.
Mostly you need to read the doc for new `shardIteratorType` consumer property.

Hope that meets your expectations.

Cheers!
