### ISSUE TITLE
not able to bind consumer group with particular shard of kinesis stream

### ISSUE THREAD

**Issue by vikrantch-hk** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#35]
I am defining consumer group and shard id like below in application.yml

```
spring:
  cloud:
    stream:
      bindings:
        ordersIn:
          destination: testhk
          group: shipping-group
          shardId: shardId-000000000001
          content-type: application/json
```
But when I am starting consumer it's showing both shard ids in shard offset. below are the startup logs
```
2018-02-14 18:12:35.547  INFO 10024 --- [           main] a.i.k.KinesisMessageDrivenChannelAdapter : started KinesisMessageDrivenChannelAdapter{shardOffsets=[KinesisShardOffset{iteratorType=TRIM_HORIZON, sequenceNumber='null', timestamp=null, stream='testhk', shard='shardId-000000000000', reset=false}, KinesisShardOffset{iteratorType=TRIM_HORIZON, sequenceNumber='null', timestamp=null, stream='testhk', shard='shardId-000000000001', reset=false}], consumerGroup='shipping-group'}
2018-02-14 18:13:04.508  WARN 10024 --- [l-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=46s178ms985µs770ns).
2018-02-14 18:13:24.911  INFO 10024 --- [esis-consumer-1] a.i.k.KinesisMessageDrivenChannelAdapter : The [ShardConsumer{shardOffset=KinesisShardOffset{iteratorType=TRIM_HORIZON, sequenceNumber='null', timestamp=null, stream='testhk', shard='shardId-000000000000', reset=false}, state=NEW}] has been started.
2018-02-14 18:13:25.022  INFO 10024 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 64399 (http) with context path ''
2018-02-14 18:13:25.027  INFO 10024 --- [           main] demo.KinesisApplication                  : Started KinesisApplication in 83.839 seconds (JVM running for 85.396)
2018-02-14 18:13:27.057  INFO 10024 --- [esis-consumer-1] a.i.k.KinesisMessageDrivenChannelAdapter : The [ShardConsumer{shardOffset=KinesisShardOffset{iteratorType=TRIM_HORIZON, sequenceNumber='null', timestamp=null, stream='testhk', shard='shardId-000000000001', reset=false}, state=NEW}] has been started.
```

**Comment by artembilan** [comment]
This isn't possible with the current implementation.

I can't say you that we are going to support this, because it isn't available in Kafka Binder as well.

I think we need to consult with @sobychacko why that is missed in the Kafka Binder and then we together will workout the solution for this issue.

Or will just close as `Won't Fix` because of some particular reason do not support such a functionality.

Thanks

**Comment by vikrantch-hk** [comment]
![binding scenario](https://user-images.githubusercontent.com/34442831/36209650-482814cc-11c2-11e8-8d06-2fb23f7dca45.jpg)

**Comment by garyrussell** [comment]
I don't see any reason not to support it (aside from resources); since the underlying frameworks support it.

I don't know how practical it would be in an environment like cloud foundry though, since each instance gets the same configuration (which is probably why it was omitted in the first place).

**Comment by artembilan** [comment]
I know what you mean @vikrantch-hk .

The situation that you don't need a separate group to consume from the different shards.
The single group will ensure that for you with the shards distribution. 
Only the problem that there is no guarantee that all shards won't go to the same consumer.

So, yes, a direct shards assignment will fix your requirements independently of the same or different consumer groups.

Right, we can add such a functionality to the consumer configuration, but first of all I would like to hear the reason why we still don't support it in Kafka Binder, @sobychacko .

Meanwhile as a workaround, @vikrantch-hk , you can use different streams with a single shard each to achieve your application requirements.

**Comment by vikrantch-hk** [comment]
@artembilan thanks

**Comment by sobychacko** [comment]
@artembilan I think this relates to static partitioning where an instance of an application can statically specify the partition it wants to. See this issue:https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/31
However, we still can't do explicit partitions. I think we can add that support to the kafka binder if that's a common requirement.

**Comment by artembilan** [comment]
Thank you for your feedback, @sobychacko!

Well, I think since this is a general requirement in , it must be pushed to the Core level alongside with the `destination` property. Something like `partition(s)`. As a part of `ConsumerProperties`.

**Comment by artembilan** [comment]
Well, according existing Apache Kafka logic, an explicit assignments of the particular partitions doesn't involve consumer group management:
```
 /**
     * Manually assign a list of partitions to this consumer. This interface does not allow for incremental assignment
     * and will replace the previous assignment (if there is one).
     * <p>
     * If the given list of topic partitions is empty, it is treated the same as {@link #unsubscribe()}.
     * <p>
     * Manual topic assignment through this method does not use the consumer's group management
     * functionality. As such, there will be no rebalance operation triggered when group membership or cluster and topic
     * metadata change. Note that it is not possible to use both manual partition assignment with {@link #assign(Collection)}
     * and group assignment with {@link #subscribe(Collection, ConsumerRebalanceListener)}.
     * <p>
     * If auto-commit is enabled, an async commit (based on the old assignment) will be triggered before the new
     * assignment replaces the old one.
     *
     * @param partitions The list of partitions to assign this consumer
     * @throws IllegalArgumentException If partitions is null or contains null or empty topics
     * @throws IllegalStateException If {@code subscribe()} is called previously with topics or pattern
     *                               (without a subsequent call to {@link #unsubscribe()})
     */
    @Override
    public void assign(Collection<TopicPartition> partitions) {
```

Since we are pursuing similar functionality here in Kinesis Binder, I would say that we are not going to implement such a functionality since it doesn't correlate with the `Consumer Group` abstraction per se.

Although we may still relax our vision a bit and provide such a functionality anyway with the note that a consumer group management is already up to end user, e.g. via global Leader Election, where only one instance could start with the provided `role`: https://docs.spring.io/spring-integration/docs/5.0.6.RELEASE/reference/html/messaging-endpoints-chapter.html#leadership-event-handling.

**Comment by dmytrodanilenkov** [comment]
@artembilan any update on this?

**Comment by artembilan** [comment]
Sorry, we didn't have a chance to look into this.

Contribution is welcome though!

**Comment by dmytrodanilenkov** [comment]
@artembilan how do you see it can be implemented? As I understand in this case I should extend the interface method     `ConsumerDestination provisionConsumerDestination(String name, String group, C properties) throws ProvisioningException;
`. Weprobably should have something like `ConsumerDestination provisionConsumerDestination(String name, String group, String shardId, C properties)` Also it's interesting that provistionConsumerDestination implemantation in KinesisStreamProvisioner class don't use groupId at all

**Comment by artembilan** [comment]
I don't think there is something relevant to the provisioner in this case. What we really need is just an option to let end-user to configure a specific shard and use exactly that shard when we create a consumer instance.

See `KinesisMessageChannelBinder` and its `createConsumerEndpoint()` impl:

```
	if (this.configurationProperties.isKplKclEnabled()) {
			adapter = createKclConsumerEndpoint(destinationToUse, group, properties);
		}
		else {
			adapter = createKinesisConsumerEndpoint(destinationToUse, group, properties);
		}
```

and its `createKinesisConsumerEndpoint()`:
```
if (CollectionUtils.isEmpty(shardOffsets)) {
			adapter = new KinesisMessageDrivenChannelAdapter(amazonKinesisClient, destination.getName());
		}
		else {
			adapter = new KinesisMessageDrivenChannelAdapter(amazonKinesisClient,
					shardOffsets.toArray(new KinesisShardOffset[0]));
		}
```

So, we do here distribute shards according instance index of your consumer application, but we don't consult here with some extra property if specific shard is provided. So, my thought is if we would have something like `shard` configuration property for the `KinesisConsumerProperties`, we would be able to propagate it down to that `KinesisMessageDrivenChannelAdapter` instance.

NOTE: KCL does not expose any option to deal with a specific shard. Therefore a feature we would could implement here would not be compatible with a KCL mode.

The provisioner must do nothing in this case probably. Or could consult with that new property for the fact that requested shard really exists in the stream. As far as I know we cannot assign specific id for the shard we can create in the stream.

Thanks for your interest in contribution!

**Comment by dmytrodanilenkov** [comment]
@artembilan also I think it will not going to work with instanceCount > 1

**Comment by artembilan** [comment]
Well, yes, the `instanceCount`  and `shardId` must be considered as mutually exclusive.
We probably can reject such a configuration during properties validation.

I think what you show so far with that logic is good.

Thank you again!

**Comment by dmytrodanilenkov** [comment]
@artembilan created PR
