### ISSUE TITLE
Auto reconnect in Kinesis

### ISSUE THREAD

**Issue by dhruvpanwar95** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#38]
When my application loses connection to aws,it doesn't reconnect.Is it supported in aws kinesis binder or do we have to add any property?

**Comment by artembilan** [comment]
I somehow thought it is a target HTTP client responsibility: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/section-client-configuration.html.

Would be great to see more context and some logs as an evidence that we lose context and go to the process in the next polling iteration. 

More over I think that the issue belongs to the [Spring Integration AWS](https://github.com/spring-projects/spring-integration-aws) project. That's where low-level `KinesisMessageDrivenChannelAdapter` lives. That's already not Kinesis Binder responsibility. It is fully based on that foundation.

Please, reopen issue there, with the link here and with more information to help me to determine "culprit".

Thanks for understanding
