### ISSUE TITLE
On resharding,The consumer has to be restarted

### ISSUE THREAD

**Issue by dhruvpanwar95** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#39]
When i do resharding,the consumer doesn't pick new shards itself.Is there any property to set?

**Comment by artembilan** [comment]
There are a couple properties on the matter:
```
private int describeStreamBackoff = 1000;

private int describeStreamRetries = 50;
```
But I don't think it is an issue.

Please, move this ticket to the [Spring Integration AWS](https://github.com/spring-projects/spring-integration-aws) project and share as much info as possible, including logs and stack traces.

Thanks for understanding.

**Comment by artembilan** [comment]
For more context. The *resharding* algorithm is fully based on the logic described here: https://docs.aws.amazon.com/streams/latest/dev/developing-consumers-with-sdk.html.

So, we have a code like in the `ShardConsumer`:
```
if (this.shardIterator == null) {
	// Shard is closed: nothing to consume any more.
	// Resharding is possible.
	stop();
}
```

and then in the main `ConsumerDispatcher` cycle:
```
if (ConsumerState.STOP == shardConsumer.state) {
	iterator.remove();
	if (KinesisMessageDrivenChannelAdapter.this.streams != null
				&& shardConsumer.shardIterator == null) {
		// Shard is CLOSED and we are capable for resharding
		KinesisShardOffset shardOffset = shardConsumer.shardOffset;
		String stream = shardOffset.getStream();
		if (KinesisMessageDrivenChannelAdapter.this.inResharding.add(stream)) {
			this.inReshardingProcess.remove(stream);
			synchronized (KinesisMessageDrivenChannelAdapter.this.shardOffsets) {
				KinesisMessageDrivenChannelAdapter.this.shardOffsets.remove(shardOffset);
			}
		}
	}
}
```

Not sure what we are missing and I really would like to see more info and some help on the matter.
But again: that is already outside of the Kinesis Binder project scope.
