### ISSUE TITLE
Productionize AWS Kinesis Binder

### ISSUE THREAD

**Issue by PedroAlvarado** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#4]
The purpose of this issue is to bring potential non-spring-core contributors, such as myself, together to help get this binder into a production ready state. 

@artembilan I'd be great if you can provide some guidance as to the necessary work to get this binder to GA v1. A simple check list would be a great starting point.

**Comment by artembilan** [comment]
Glad to hear, @PedroAlvarado !

And thank you for the for proposition of the help.

I'm coming back to this project the next week.

Together with @sabbyanandan we will fill out GH issues what are necessary to do so far.

Meanwhile I'd be glad to start from the `DynamoDbMetadataStore` in the Spring Integration AWS for offset tracking: https://github.com/spring-projects/spring-integration-aws/issues/64

Let's park this ticket for the GA release point!

**Comment by sabbyanandan** [comment]
Hi, @PedroAlvarado: Thanks for reaching out and offering to help! 

@artembilan and I recently discussed the next steps. From the community support like yours, we would be all the more comfortable in putting efforts to collaborate and graduate this binder implementation.

More on this soon.

**Comment by spjegan** [comment]
Hi @PedroAlvarado @sabbyanandan Thanks for the wonderful work. I have a quick question. Is this Kinesis binder ready to be used in a production application?

**Comment by artembilan** [comment]
(Typing from phone, so sorry for rude language).

No, it’s not. Just because it is based on SNAPSHOT dependencies. So, the work isn’t done yet.

Thank you for the interest though!

**Comment by spjegan** [comment]
@artembilan Thanks for the quick response. I would love to use this. Do you have any timeline when this will be ready?

**Comment by artembilan** [comment]
Well, we may do Milestone 1 the next week, but you should be ready to use a lot Milestone dependencies...

**Comment by artembilan** [comment]
The point is: we can’t go GA until all our dependencies not GA.

**Comment by artembilan** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/commit/391f2f3bd16f5e2f3bca525ca086c699f7352698
