### ISSUE TITLE
Change the URL of the kinesis broker for local testing

### ISSUE THREAD

**Issue by peletomi** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#41]
is there a possibility to change the address of the kinesis broker for local testing. For example using localstack.

thanks

**Comment by artembilan** [comment]
Not sure what is the problem though, but `KinesisBinderConfiguration` has the code like:
```
@Bean
@ConditionalOnMissingBean
public AmazonKinesisAsync amazonKinesis(AWSCredentialsProvider awsCredentialsProvider,
		RegionProvider regionProvider) {
```
So, if you declare an `AmazonKinesisAsync` bean in your application context, this one won't work. And already there you can do whatever you need with Kinesis and entire AWS client.

For example that's how I use `kinesalite` for local testing:
```
@ClassRule
public static LocalKinesisResource localKinesisResource = new LocalKinesisResource();
...
@Bean
public AmazonKinesisAsync amazonKinesis() {
	return localKinesisResource.getResource();
}
```
See `KinesisBinderProcessorTests` in the project: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/master/spring-cloud-stream-binder-kinesis/src/test/java/org/springframework/cloud/stream/binder/kinesis/KinesisBinderProcessorTests.java

**Comment by peletomi** [comment]
Maybe I was not correct in describing. I want to use kinesalite for local development, so that I don't have to send data to kinesis. 

I was hoping there is a variable like for kafka: spring.cloud.stream:kafka.binder.brokers with which I can set the URL to the local running kinesalite.

**Comment by artembilan** [comment]
??? As far as I know, that's not so simple for AWS services. Therefore no configuration properties and you should just provide an appropriate bean. 

This is how I build client for kinesalite to make it working with my tests:
```
// See https://github.com/mhart/kinesalite#cbor-protocol-issues-with-the-java-sdk
System.setProperty(SDKGlobalConfiguration.AWS_CBOR_DISABLE_SYSTEM_PROPERTY, "true");

this.resource = AmazonKinesisAsyncClientBuilder.standard()
		.withClientConfiguration(
				new ClientConfiguration()
						.withMaxErrorRetry(0)
						.withConnectionTimeout(1000))
		.withEndpointConfiguration(
				new AwsClientBuilder.EndpointConfiguration("http://localhost:" + this.port,
						Regions.DEFAULT_REGION.getName()))
		.withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials("", "")))
		.build();
```
So, can it be configured just with a property?

**Comment by artembilan** [comment]
Right, my test config mentioned above looks like:
```
@EnableBinding(Processor.class)
@EnableAutoConfiguration(exclude = ContextResourceLoaderAutoConfiguration.class)
public static class ProcessorConfiguration {

	@Bean
	public AmazonKinesisAsync amazonKinesis() {
		return localKinesisResource.getResource();
	}

	@Bean
	public MetadataStore kinesisCheckpointStore() {
		return new SimpleMetadataStore();
	}

	@Transformer(inputChannel = Processor.INPUT, outputChannel = Processor.OUTPUT)
	public String transform(Message<String> message) {
		String payload = message.getPayload();
		if (!"junk".equals(payload)) {
			return payload.toUpperCase();
		}
		else {
			throw new IllegalStateException("Invalid payload: " + payload);
		}
	}

	@Bean(name = Processor.INPUT + "." + CONSUMER_GROUP + ".errors")
	public SubscribableChannel consumerErrorChannel() {
		return new PublishSubscribeChannel();
	}
...
}
```
where that `localKinesisResource.getResource()` comes from the:
```
@ClassRule
public static LocalKinesisResource localKinesisResource = new LocalKinesisResource();
```
And code of that class you can get from here: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/master/spring-cloud-stream-binder-kinesis/src/test/java/org/springframework/cloud/stream/binder/kinesis/LocalKinesisResource.java

Not sure what I am missing describing the solution for you...

**Comment by peletomi** [comment]
Thank you! I will try this out.
