### ISSUE TITLE
When is the release version date?

### ISSUE THREAD

**Issue by stavalfi** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#43]
Hi,

What is the approximate date of the release version of kinesis-binder?

**Comment by artembilan** [comment]
When the Spring Cloud Stream 2.0 GA is [available](https://github.com/spring-cloud/spring-cloud-stream/milestone/32), we are going to release Milestone 2 for this Kinesis Binder.

Not sure though when GA will be done for this project.
It depends on the [Spring Integration AWS](https://github.com/spring-projects/spring-integration-aws) and there is some hard work to do yet...

Any contribution and help is welcome to expedite a general availability of that and this project!

**Comment by stavalfi** [comment]
Thanks for the fast response!

Does this project is part of spring cloud stream?

**Comment by artembilan** [comment]
If you are talking about a "release train", then no. It's still not. But once we come to GA here, it will be included to train as well. 

But on the other hand it is indeed a part of the Spring Cloud Stream portfolio.
