### ISSUE TITLE
Stream Binder Integration with AWS Lambda?

### ISSUE THREAD

**Issue by pclements12** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#48]
Haven't really dug deeply into the implementation details or the application model of the spring cloud stream binder abstraction, so forgive me if this is obvious but I'm curious if it could be possible to use the binder in an event-driven fashion with AWS lambda functions?

I suppose for consuming, the binder is basically useless since AWS Lambda and Kinesis can natively perform that polling and triggering process?

But for producers from Lambda (using Java/Spring), could they properly use the Spring Integration channel adapters from the Kinesis binder to publish messages?

**Comment by pclements12** [comment]
Yea makes sense, the approach seems a little strange, but it's because I'm considering the possibility of creating a spring cloud data flow runtime that leverages lambda. Dataflow uses the spring binder to connect parts of a stream. 

It also expects each app in a stream to be a spring boot app, so it's a little bit of a shoehorn to make it fit for Lambda as a spring boot app.

When an app starts up using the binder and a source or sink is specified, is the app responsible for creating the stream sink and source "queues"? 

I saw the auto create option so I assume you could specify whether or not the spring boot app should attach to an existing or be responsible for creating its own. 

I think that in spring cloud data flow,  the apps also are responsible for creating stream connections, which could be a problem in the case of lambda.

Thanks for the info!

**Comment by artembilan** [comment]
Well, the problem of Lambda that it is short-lived handler instantiated by the trigger, meanwhile any Spring Cloud Stream is long-lived fully independent application which is read to consume events from the Binder and produce if necessarily.  

I would say AWS Lambda (or any Servless) doesn't fit this model and can't be used as part of transport. It can't be used as a `processor` (or function) in between, or as a `sink`  - the last step in the stream. But it definitely isn't good for sourcing.

At least that is my feeling. I might be wrong though...

**Comment by pclements12** [comment]
Yep, understood. I will probably have to setup the event triggers manually for processors and sinks to receive messages, but would be able to allow the kinesis binder to handle connections of producers.

We'll see. I'm asking around on the dataflow gitter to see what the guys there think. 

Thanks for your help

**Comment by artembilan** [comment]
Sure! Please, come back with the reasonable feedback!

May we close the issue for now though?

**Comment by pclements12** [comment]
Sure!
