### ISSUE TITLE
1.0.0.M2 not found in libs-snapshot

### ISSUE THREAD

**Issue by komushi** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#50]
neither in libs-snapshot-local
How should I set the repository to include it?

Thanks

**Comment by artembilan** [comment]
It is in the `/libs-milestone`: http://repo.spring.io/libs-milestone/org/springframework/cloud/spring-cloud-stream-binder-kinesis/1.0.0.M2/

Maybe you use a wrong dependency?
There is no `core` and `starter` modules anymore. They are redundant and just bring extra empty layer.
Everything you is like this:
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-stream-binder-kinesis</artifactId>
	<version>1.0.0.M2</version>
</dependency>
```

**Comment by komushi** [comment]
Thanks for the prompt response.

Use binder instead of spring-cloud-starter-stream-kinesis?

```
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-stream-kinesis</artifactId>
        <version>1.0.0.M2</version>
    </dependency>
```
