### ISSUE TITLE
Support partitionKeyExpression

### ISSUE THREAD

**Issue by jihlee** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#52]
**kinesis binder version**: 1.0.0.M2

I found out that Kinesis binder does not support configuration of partition currently.
I set up spring.cloud.stream.bindings.output.producer.partitionKeyExpression properties, but partition key sent to Kinesis was not changed but it was like "partitionKey-0".

It seems that Kinesis binder does not use partitionKeyExpression properties and set partitionKeyExpression as 'partitionKey-headers["scst_partition"]' 

Kinesis's message sequence number monotonically increases only in shard; the missing feature could be potentially dangerous to application whose the order of messages should be guaranteed.

Is there any issue or suggestion among this?

**References**
https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_partitioning
https://docs.aws.amazon.com/streams/latest/dev/key-concepts.html#shard
https://forums.aws.amazon.com/thread.jspa?threadID=216870 
https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/ea8d5652f5ab1091179fa0556f616ab13d4d3cdf/spring-cloud-stream-binder-kinesis/src/main/java/org/springframework/cloud/stream/binder/kinesis/KinesisMessageChannelBinder.java#L121

**Comment by jihlee** [comment]
I guess this link is the same issue
https://stackoverflow.com/questions/49253112/how-to-set-partitionkey-when-using-spring-cloud-stream-kinesis

**Comment by artembilan** [comment]
@sobychacko ,

Would you mind to help here to explain how partitioning works in Spring Cloud Stream?
I some how lost in all that hard logic around `PartitionHandler` and `BinderHeaders.PARTITION_HEADER` & `BinderHeaders.PARTITION_OVERRIDE`.

Thanks

**Comment by artembilan** [comment]
For some background do not lose useful info: https://stackoverflow.com/questions/31893297/how-to-determine-shard-id-for-a-specific-partition-key-with-kcl.

From here I think we should end up with the custom partition evaluation function for this Kinesis Binder. Do not rely what we have so far for Kafka Binder.

**Comment by artembilan** [comment]
See my answer there in the mentioned above StackOverflow question.

To be honest we are going to fix it here on the Kinesis Binder level similar way. Or will remove the `PartitioningInterceptor` altogether or will bypass it some other way to let the proper Kinesis shard selection logic to work properly. 

Thank you for the report and sorry for delay: it took some time for us to come up with understanding the feature!

**Comment by artembilan** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/commit/6456e0ab9d0fbfc634430d7a1db48c6dccc7e4a8
