### ISSUE TITLE
Unable to convert the payload to object when using Rabbit MQ

### ISSUE THREAD

**Issue by santoov** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#58]
Hi Team,
I'm trying to receive queue using spring AMQP from rabbit server which was placed by third party (thru JMS clent), I could see Message object but could not convert the payload to RMQMapMessage, as it is getting a byte array, even de-serialization also did not work, please help me over here

**Comment by artembilan** [comment]
Sorry, but your issue doesn't sounds like related to the https://aws.amazon.com/kinesis[AWS Kinesis] or even just to https://cloud.spring.io/spring-cloud-stream[Spring Cloud Stream].

Please, consider to raise your issue on some community forum, e.g. StackOverflow. We don't handle here on GitHub questions.

Closing as `Invalid`
