### ISSUE TITLE
Option to disable automatic stream creation

### ISSUE THREAD

**Issue by dittos** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#59]
It would be nice to have such option to prevent streams being created accidentally, as streams are charged resource.

**Comment by artembilan** [comment]
Your concern is not clear. How is it going to work if there is just no Kinesis stream to interact with?
The logic is like this:
```
catch (ResourceNotFoundException e) {
			if (logger.isInfoEnabled()) {
				logger.info("Stream '" + stream + "' not found. Create one...");
			}

			this.amazonKinesis.createStream(stream, Math.max(this.configurationProperties.getMinShardCount(), shards));
			continue;
}
```

So, we create only if requested stream doesn't exist in AWS yet.

If you would like to disable even this, then all the stuff about Kinesis Binder is useless in your application and you should consider to disable it altogether.

Your request is very confusing. Sorry...
I'd prefer to stay with the current implementation.

Please, share more arguments.

Thanks for understanding.

**Comment by artembilan** [comment]
Closed as `Won't Fix` since there is no any feedback so far and we treat the current implementation as correct.

Thanks
