### ISSUE TITLE
Add support for DynamoDB Data Streams

### ISSUE THREAD

**Issue by kgrodzicki** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#62]
Hi there,

as in the title. Has it been tested with dynamoDB streams ?

**Comment by artembilan** [comment]
No, it has not been tested, but looks like we can use this Kinesis Adapter: https://github.com/awslabs/dynamodb-streams-kinesis-adapter to provide our own `amazonKinesis` bean to override one provided in the Binder configuration.
Although I see they don't provide an `AmazonKinesisAsync` implementation, so it might be a bit cumbersome to walk that way...

Any thoughts from you?
What is your point so far?
Aren't there a way to remap DynamoDB streams into Kinesis streams on the AWS level, not client application?

**Comment by kgrodzicki** [comment]
Thanks for your answer. I did not get it to work with spring-cloud-stream. Have used lambda implementation so far. "Remapping" a DynamoDB stream to kinesis is not a solution in my case.

**Comment by artembilan** [comment]
I think the use-case is valid and really has to be supported here (or even on the SI-AWS level).
So, reopening for the future consideration...
