### ISSUE TITLE
WARN 5 --- [esis-consumer-1] a.i.k.KinesisMessageDrivenChannelAdapter : GetRecords request throttled

### ISSUE THREAD

**Issue by sidath80** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#67]
Hello Team,

I am getting following warning when connect to the stream called stream-dev.
Please let me know and guidance for this warning.
```
WARN 5 --- [esis-consumer-1] a.i.k.KinesisMessageDrivenChannelAdapter : GetRecords request throttled for [ShardConsumer{shardOffset=KinesisShardOffset{iteratorType=LATEST, sequenceNumber='null', timestamp=null, stream='stream-dev', shard='shardId-000000000001', reset=false}, state=CONSUME}] with the reason: Rate exceeded for shard shardId-000000000001 in stream stream-dev under account 3456778.
```
Thanks
Sidath

**Comment by artembilan** [comment]
See AWS `ProvisionedThroughputExceededException` description: https://docs.aws.amazon.com/streams/latest/dev/kinesis-record-processor-additional-considerations.html

> Each shard has a read throughput of up to 5 transactions per second for reads, up to a maximum total data read rate of 2 MB per second. If an application (or a group of applications operating on the same stream) attempts to get data from a shard at a faster rate, Kinesis Data Streams throttles the corresponding Get operations. 

So, that sounds like you try to read poll the shard much faster, than it is allowed by Kinesis.
I most cases this happens that you have several consumers for the same shard.

You can consider to play with the:

```
	/**
	 * The sleep interval in milliseconds used in the main loop between shards polling cycles.
	 * Defaults to {@code 1000}l minimum {@code 250}.
	 * @param idleBetweenPolls the interval to sleep between shards polling cycles.
	 */
	public void setIdleBetweenPolls(int idleBetweenPolls) {
		this.idleBetweenPolls = Math.max(250, idleBetweenPolls);
	}
```
As you see the minimum is `250` milliseconds. You may configure it for `1 sec` for better throttling.

There is nothing more the Framework can help you. You just break an AWS policy therefor such a warn. But at the same time it doesn't mean that your application doesn't work.

**Comment by sidath80** [comment]
Thanks you very much, Is there any way to stop this WARN message from the application.

Thanks
Sidath

**Comment by artembilan** [comment]
You can just configure an `ERROR` logging level for the `org.springframework.integration.aws.inbound.kinesis` category.

I don't see reason to have such a config option since I found this situation as abnormal and something has to be fixed on the application level.

I'm treating this question as fixed and closing the issue.
