### ISSUE TITLE
Please Provide kinesis_binder_checkpoint_table's default hashKey

### ISSUE THREAD

**Issue by Venkat2811** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#68]
Hello Team,

Excellent work with on kinesis binder !

Documentation has to be updated to provide `kinesis_binder_checkpoint_table` (SpringIntegrationMetadataStore) default `hashKey`

Running locally, it created a SpringIntegrationMetadataStore DDB table in our QA Env and I found that `KEY` is the hashKey.

Thanks,
Venkat

**Comment by artembilan** [comment]
Hi, @Venkat2811 !

Sorry, not clear what you are asking.
Please, provide more info what you would like to see configurable.

Although it sounds more like a request for the `DynamoDbMetadataStore` hosted in the https://github.com/spring-projects/spring-integration-aws

Thanks

**Comment by artembilan** [comment]
Well, good catch!

I think we definitely need to go ahead and expose a `partitionKey` for the `DynamoDbMetadataStore`. Fully similar what we have for the `DynamoDbLockRegistry`.
And afterward such an option will be exposed here on the Binder level for external configuration!

Sounds like a time to start a `2.1` version for Spring Integration AWS and `1.1` for this Kinesis Binder!

Contribution is welcome!

**Comment by Venkat2811** [comment]
Thanks !

**Comment by artembilan** [comment]
@Venkat2811 ,

As we agreed in the linked issues, it turned out as exactly a docs concern in this project.

Feel free to contribute the fix here!

Thank you!
