### ISSUE TITLE
from single spring boot can connect to Multible kinesis stream

### ISSUE THREAD

**Issue by sidath80** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#69]
Hello Team,

I have couple of questions,

 1 .Is it possible to connect to multiple kinesis stream from single spring boot application ?
2. How do we connect to the kinesis stream from jboss (which is not using spring boot  and it has only latest spring core related libs)?
3. What is the different between  two dynamo tables called checkpoint and lock. I don't see any data in the lock table.

Really appreciate your quick response for our questions/concerns  :)

Thank you
Sidath

**Comment by artembilan** [comment]
The `spring.cloud.stream.bindings.[CHANNEL_NAME].destination` can be specified as a *comma-separated-value*.
See Spring Cloud Stream Docs on the matter: https://docs.spring.io/spring-cloud-stream/docs/Fishtown.M3/reference/htmlsingle/#binding-properties

> **destination**

>    The target destination of a channel on the bound middleware (for example, the RabbitMQ exchange or Kafka topic). If the channel is bound as a consumer, it could be bound to multiple destinations, and the destination names can be specified as comma-separated String values. If not set, the channel name is used instead. The default value of this property cannot be overridden.


A JBOSS concern is out of this project scope. Of course, you can pack some simple Spring Boot `war` and deploy it into JBOSS as a regular application. All the logic will be encapsulated in your app and JBOSS won't be aware that it is a Spring Boot app.
See more info in the Spring Boot Docs: https://docs.spring.io/spring-boot/docs/2.0.6.RELEASE/reference/htmlsingle/#howto-create-a-deployable-war-file

Please, consider in the future do not ask questions here on GitHub, but on some community forum, e.g. StackOverflow.
We handle here only bugs and feature requests.

Thank you for understanding!

**Comment by sidath80** [comment]
sorry one last question ,

3. What is the different between two dynamo tables called checkpoint and lock. I don't see any data in the lock table.

Thanks
Sidath

**Comment by artembilan** [comment]
See documentation: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/master/spring-cloud-stream-binder-kinesis-docs/src/main/asciidoc/overview.adoc

> The support of this feature is implemented as a part of MetadataStore key for shard checkpoints in the KinesisMessageDrivenChannelAdapter - [CONSUMER_GROUP]:[STREAM]:[SHARD_ID]. In addition the LockRegistry is used to ensure exclusive access to each shard. This way only one channel adapter in the same consumer group will consumer messages from a single shard in the stream it is configured for.

The `checkpoint` table is used for storing consumed sequence do not read it again from a new consumer in the future.
The `lock` is used for exclusive access for a single shard, so only one consumer is going to deal with one shard at a time.

**Comment by sidath80** [comment]
Thank you ver much .... sorry for disturbing you :)
