### ISSUE TITLE
Would like to add this annotation @Bean to the spring framework

### ISSUE THREAD

**Issue by chinalihui** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#7]
demo:
@Beans
public abstract class ApplicationBeans {
	
	@Bean(classes="org.apache.commons.dbcp.BasicDataSource",
			propertys={
			@Property(name="driverClassName",value="com.mysql.jdbc.Driver"),
			@Property(name="url",value="${mysql.db.url}"),
			@Property(name="username",value="username"),
			@Property(name="password",value="123456")
			}
	)
	Object dataSource;
	
	@Bean(initMethodName="initMethod",destroyMethodName="destroyMethod",scope=Bean.BEAN_SCOPE_PROTOTYPE,
			propertys={
                                @Property(name="testBean",ref="testBean"),
				@Property(name="name",value="123333"),
				@Property(name="password",value="${actiontopic}"),
				@Property(name="address",value=Bean.BEAN_SCOPE_REQUEST),
				@Property(name="count",value="888"),
				@Property(name="list",list={
	 					@Element("AAA"),
	 					@Element("BBB"),
	 					@Element("CCC"),
	 					@Element("DDDd"),
				}),
				@Property(name="map",map={
						@Entry(key="K1",value="V111"),
						@Entry(key="K2",value="V222"),
						@Entry(key="K3",value="V333")
				})
	}) TestObject testObject;
	
	@Bean(propertys={
			@Property(name="id",value="123")
	}) ExpInfo expInfo;

This is demo, this annotation has been used for our online environment, whether it is appropriate;
@ Beans, @ Bean, @ Property, @ Element, @ Entry; The above is our custom annotation, the process is to convert the above @Bean BeanDefinition added to the Spring ApplicationContext applicationContext.registerBeanDefinition (beanId, bdb.getBeanDefinition ()) , So that the application can rely on the @Bean annotation of the Bean instance；
Thus replacing the spring xml configuration file；
If you can, hope to join the Spring Framework

**Comment by artembilan** [comment]
Unfortunately, this is fully unrelated to this **Spring Cloud Stream AWS Kinesis Binder** project and there is already a `@Configuration` annotation and its friends for a while: http://docs.spring.io/spring/docs/current/spring-framework-reference/html/beans.html#beans-java.

And yes, they fully replace the XML configuration file.

Please, be careful in the future where you post your concerns.
We use GitHub issues only for bugs and new feature requests. But anyway they have to be related to the particular project.
