### ISSUE TITLE
java.nio.charset.MalformedInputException: Input length = 1

### ISSUE THREAD

**Issue by sidath80** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#71]
Hello Team,

We are produce messages from the Spring boot with (spring -kinesis) library and consume using AWS KCL library directly.
When we consuming message from the kinesis we are getting following error.

```ava.nio.charset.MalformedInputException: Input length = 1
java.nio.charset.MalformedInputException: Input length = 1
14:54:49
at java.nio.charset.CoderResult.throwException(CoderResult.java:281) ~[?:1.8.0_181]
14:54:49
at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:816) ~[?:1.8.0_181]```

We already add following settings to the producer in spring boot .

spring:
  cloud:
    stream:
        bindings:
          ordersOut:
            destination: pexa-event-stream-dev
            content-type: application/json
          producer:
            headerMode: none
            useNativeEncoding: true


Is this problem because of the decode/encryption method  with the spring boot producer??
I have added following properties to avoid this issue,

  headerMode: none
  useNativeEncoding: true
but still i am getting same error.

sample json we received 
``````ÿ^A^KcontentType^@^@^@^R"application/json" {}
json come with header , we need to avoid this header.

Thanks
Sidath

**Comment by artembilan** [comment]
Please, revise your post.
It is not readable and I'm not sure what is the code there, but what is just text to edit your post myself.

To avoid `embeddedHeaders` you need to configure this property: `spring.cloud.stream.bindings.<channelName>.producer.headerMode = none`: https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_producer_properties

Please, reconsider your YAML on the matter.

And also start, please, questions from StackOverflow. 
We will say you there if that is a bug and should be raised as an issue here.
