### ISSUE TITLE
No retry logic for Pushing Failed Messages to Kinesis using Spring Cloud Stream in Case of "Maximum Throughput Exceeded Exception" on Kinesis end

### ISSUE THREAD

**Issue by Saurabh789789** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#73]
I am using spring cloud stream to push messages to kinesis, although I am able to push messages to kinesis stream successfully, the messages are failing on the Kinesis side with Throughput Exceeded Exception.I don't see any way to retry pushing these messages or to know which message has failed while using Spring Cloud Stream libs (unlike how KPL or KCL provides with PutRecordRequest).
How to know  which record has failed on the Kinesis end using only Spring Cloud Stream libraries to push to kinesis and retry these failed messages.

**Comment by Saurabh789789** [comment]
@artembilan Can you help?

**Comment by olegz** [comment]
@Saurabh789789 there is no need to double-post, re-post, post in many different places etc. This will only pave the path fr you to be black listed. We are the developers and the community that live in multiple timezones. Artem is sleeping at the moment and he has work to do as well. He will certainly reply in due time. If this is something urgent and you are a customer please use your standard support channels.

**Comment by artembilan** [comment]
The same StacfkOverflow question: https://stackoverflow.com/questions/53581149/retry-pushing-messages-to-kinesis-using-spring-cloud-stream-libraries.
