### ISSUE TITLE
How to set shardIteratorType based on a database value after startup

### ISSUE THREAD

**Issue by chiku80** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#77]
Hi,
I apologize if this the wrong place to ask this question. If so then please direct me to the correct area. 
I am successfully the aws kinesis binder in a spring boot app that acts as a consumer. In the properties file currently i set the `shardIteratorType` to LATEST. However, i am trying to work out the correct solution for the following use case. 

Lets say my spring boot app stops all of a sudden for whatever reason (memory problem or aws ec2 going away...). I now have to restart my kinesis consumer app. during the restart lets say that messages were produced to the kinesis queue by another app. These messages will not be picked up by the spring boot consumer app so long unless I set the `shardIteratorType` to `AT_TIMESTAMP:<NOW MINUS TIME IT TOOK TO RESTART CONSUMER>>` I have to do this manually by setting the configuration property. This is tedious. Instead I would like to store the last timestamp or the last sequence number consumed in a database. Then when the consumer app is  restarted, before the kinesis consumer bean is configured i would like to query the database for this value and then only configure the kinesis consumer bean. Is this possible? Which bean would i configure and what kinesis binder autoconfiguration would i need to turn off for doing this?

**Comment by chiku80** [comment]
Please ignore my question.... I think i figured out what i have to do. 
I will set the consumer group value to a static value and shardIterator type by default is TRIM_HORIZON... so any messages that are produced while the consumer is down should be consumed after the consumer restarts. 

Please close this item if my understanding is correct. Tested it...and it worked

**Comment by artembilan** [comment]
I think your understanding is fully correct.
If consumer is lagging, the `TRIM_HORIZON` should do the trick to catch up.

Regarding some external configuration instead of static properties you should take a look into the Spring Cloud Config functionality: https://cloud.spring.io/spring-cloud-static/spring-cloud-config/2.1.0.RELEASE/single/spring-cloud-config.html

**Comment by chiku80** [comment]
thankyou!
