### ISSUE TITLE
Investigate how Checkstyle should work

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#8]
We have now `maven-checkstyle-plugin` definition, but that is unclear why we don't have `checkstyle.xml`.

The same I see in the Rabbit and Kafka Binder implementations.

What I can say it doesn't validate require `this.` for now at least.

**Comment by mbogoevici** [comment]
For Kafka and Rabbit we use the Spring Cloud checkstyle definitions. We could add checkstyle per-project or use the Spring Cloud Stream checkstyle settings (from `spring-cloud-stream-build-tools`)

**Comment by artembilan** [comment]
After offline discussion with @mbogoevici , it looks like would be better to depend on the Spring Cloud Stream Checkstyle rules from the https://github.com/spring-cloud/spring-cloud-stream/tree/master/spring-cloud-stream-tools
