### ISSUE TITLE
Question: Extracting Headers

### ISSUE THREAD

**Issue by chiku80** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#86]
I am writing a spring cloud stream consumer on a stream. I have the following method on the handler side:

```
@StreamListener(OpJobOracleBinding.ORACLE_EVENTS_TARGET)
  public void processOracleEvent(String opJobString, @Headers MessageHeaders headers) {
    try {
      log.info("Headers received: " + headers);
      log.info("Received event from binding:" + opJobString);
    } catch (Exception e) {
      log.error("error");
    }
  }
```

This works well. 
```
Headers received: {contentType=text/plain, id=8bcf290a-2c5f-3645-b07d-bafac2a7ad63, timestamp=1553391529005}
2019-03-23 18:38:49.005  INFO 97281 --- [   scheduling-1] com.example.producer.TestConsumer        : Received event from binding:TestMessage-Content
```

However, the producer application writing to the stream is outside my control. A third party team is writing to the stream. And they are not using spring cloud stream to do it. They are using the Java KCL library. I am trying to get the `aws_receivedSequenceNumber` value to be logged on the consumer side. But seems like this header is not present. How do i obtain the value of this header before the message hits the stream listener ? 

If i write my own producer using spring cloud stream i am able to the see the `aws_receivedSequenceNumber` header on the consumer side. 

I am using spring cloud stream kinesis version : `1.2.0.BUILD-SNAPSHOT` and spring cloud version is `Greenwich.SR1`

**Comment by artembilan** [comment]
What is your `listenerMode` for the consumer in properties: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/master/spring-cloud-stream-binder-kinesis-docs/src/main/asciidoc/overview.adoc#kinesis-consumer-properties ?

If it is `batch`, then you definitely don't get that value for the whole list of records.

Any simple project to reproduce the issue ?

**Comment by artembilan** [comment]
Closed as *Invalid* with the lack of feedback from the reporter.

**Comment by chiku80** [comment]
@artembilan  I am so sorry i did not get around to creating my test project for this. Can we reopen this issue? 
I was tied up doing other things.  I have created a repo to reproduce the issue. 
Checkout the repo : https://github.com/chiku80/sp-cloud-test
There is a readme file in the root repo that explains how to run the test.

**Comment by artembilan** [comment]
You say there:

> In the consumer window you will see the following log statments: 
```
Headers received: {aws_shard=shardId-000000000000, id=91b27ecb-1b6f-ffe8-d629-e9db8a942632, contentType=text/plain, aws_receivedPartitionKey=default, aws_receivedStream=bdata-test-oracle-opjob, aws_receivedSequenceNumber=49595094626030123609261409294557697561813201785160990722, timestamp=1556400419935}
```

But why you say next:
> Note that the consumer logs do not receive the `aws_receivedSequenceNumber` header value.

What is then that `aws_receivedSequenceNumber=49595094626030123609261409294557697561813201785160990722` is about ?

Sorry, I'm confused...

**Comment by chiku80** [comment]
aah... wow. I must be going crazy... You are right. Looks like this does infact work . I guess this ticket can stay closed.! Thanks for the quick response!
