### ISSUE TITLE
Question: Checkpoint mode and callbacks

### ISSUE THREAD

**Issue by nathanmesser** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#96]
Is there anyway of hooking into the checkpointing lifecycle?

I notice the docs refer to being able to use a Checkpointer callback if the checkpoint mode is manual, but I can't find any information on how to set that up in a Spring Cloud Stream environment.

**Comment by artembilan** [comment]
That must be configured via `spring.cloud.stream.kinesis.bindings.[BINDING_TARGET].consumer.checkpointMode = manual` property: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/master/spring-cloud-stream-binder-kinesis-docs/src/main/asciidoc/overview.adoc#kinesis-consumer-properties

The `Checkpointer` callback is going to appear as a `AwsHeaders.CHECKPOINTER` message header, which you can get access into from your `@StreamListener`:

```
@StreamListener
public void handleRecord(Object payload, @Header(AwsHeaders.CHECKPOINTER) Checkpointer checkpointer)
```

Then whenever you need to checkpoint you call that callback.

**Comment by artembilan** [comment]
Closed as *solved* because of explanation and leak of feedback from the reporter.

**Comment by fireboy1919** [comment]
Shouldn't there be some documentation actually describing this?

Also, stream listener is deprecated, so presumably this is not the mechanism that one would use to do this.
