### ISSUE TITLE
writing performance after 1.2.0.Release looks worse 

### ISSUE THREAD

**Issue by TetianaZa** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#99]
After the new release the performance of my application  was significantly decreased . 
We have one Producer which send messages to topic with 3 shard.
**With version 1.0.0** performance was  :  28616 messages/minute ~ 477 messages/second, processing time for 1 message 16.96ms .
**With version 1.2.0** :  3768  messages/minute ~ 63 messages/second,  processing time for 1 message 137ms.
Looks like it takes more time to put message to kinessis  with kpl . 
When set kpl-kcl-enabled: false  I got performance I had with 1.0.0 version.

My configuration : 
spring:
  cloud:
      stream:
        bindings:
          avro-kinesis-testing-out-stream:
            destination: ${app.kinesis.stream.name}
            content-type: application/*+avro
            binder: kinesis

        kinesis:
          binder:
            checkpoint:
              create-delay: 0
              table: ${app.kinesis.checkpoint.name}
            kpl-kcl-enabled: true
          bindings:
             avro-kinesis-testing-out-stream:
              producer:
                partitionKeyExpression: "ID"
                sync: true
                RecordMaxBufferedTime: 1

**Comment by artembilan** [comment]
I think that's not what we can do on our side.
This already a question of pure Kinesis producer and the mentioned Kinesis Producer Library.

Please, consider to raise such an issue in the appropriate project.
That's not what we can support on our side.

Thank you for understanding.
